export type University = {
  id: string;
  name: string;
  city: string;
  state: string;
  region: string;
  /** US News 2026 national rank from CDS workbook; null if unranked in source. */
  usNewsRank: number | null;
  /** Fraction 0–1; null when CDS reports NA. */
  acceptanceRate: number | null;
  avgGpa: number | null;
  satMid: number | null;
  actMid: number | null;
  /** Best available tuition (single / OOS / in-state) in USD. */
  tuitionUsd: number | null;
  setting: string;
  interests: string;
  personalityFit: string;
  extracurricularFit: string;
  vrTourUrl: string;
  cdsUrl: string;
  websiteUrl: string;
  sizeBand: string;
};

/** Seeded from CDS_109_Universities_Consolidated_Statistics.csv (109 schools). */
export const UNIVERSITIES: University[] = [
  {
    "id": "princeton-university",
    "name": "Princeton University",
    "city": "Princeton",
    "state": "NJ",
    "region": "Northeast",
    "usNewsRank": 1,
    "acceptanceRate": 0.044,
    "avgGpa": 3.96,
    "satMid": 1530,
    "actMid": 35,
    "tuitionUsd": 62400,
    "setting": "Suburban",
    "interests": "engineering,public policy,research",
    "personalityFit": "intellectual,ambitious",
    "extracurricularFit": "research,debate,service,athletics",
    "vrTourUrl": "https://admission.princeton.edu/visit-princeton/virtual-visit",
    "cdsUrl": "https://www.collegedata.fyi/",
    "websiteUrl": "https://www.princeton.edu/",
    "sizeBand": "Medium"
  },
  {
    "id": "massachusetts-institute-of-technology",
    "name": "Massachusetts Institute of Technology",
    "city": "Cambridge",
    "state": "MA",
    "region": "Northeast",
    "usNewsRank": 2,
    "acceptanceRate": 0.046,
    "avgGpa": null,
    "satMid": 1545,
    "actMid": null,
    "tuitionUsd": null,
    "setting": "Urban",
    "interests": "engineering,CS,physics,innovation",
    "personalityFit": "analytical,innovator",
    "extracurricularFit": "research,hackathons,robotics,maker",
    "vrTourUrl": "https://mitadmissions.org/visit/virtual-programs/",
    "cdsUrl": "https://www.gradgpt.com/common-data-set",
    "websiteUrl": "https://www.mit.edu/",
    "sizeBand": "Medium"
  },
  {
    "id": "harvard-university",
    "name": "Harvard University",
    "city": "Cambridge",
    "state": "MA",
    "region": "Northeast",
    "usNewsRank": 3,
    "acceptanceRate": 0.042,
    "avgGpa": 4.22,
    "satMid": null,
    "actMid": 35,
    "tuitionUsd": null,
    "setting": "Urban",
    "interests": "government,law,medicine,research",
    "personalityFit": "ambitious,leader",
    "extracurricularFit": "debate,research,community service,politics",
    "vrTourUrl": "https://college.harvard.edu/admissions/visit/virtual-tour",
    "cdsUrl": "https://www.collegedata.fyi/",
    "websiteUrl": "https://www.harvard.edu/",
    "sizeBand": "Large"
  },
  {
    "id": "stanford-university",
    "name": "Stanford University",
    "city": "Stanford",
    "state": "CA",
    "region": "West",
    "usNewsRank": 4,
    "acceptanceRate": 0.038,
    "avgGpa": 3.94,
    "satMid": 1550,
    "actMid": 35,
    "tuitionUsd": 67731,
    "setting": "Suburban",
    "interests": "CS,engineering,entrepreneurship,research",
    "personalityFit": "ambitious,innovator",
    "extracurricularFit": "research,robotics,startups,debate",
    "vrTourUrl": "https://tour.stanford.edu/",
    "cdsUrl": "https://www.collegedata.fyi/",
    "websiteUrl": "https://www.stanford.edu/",
    "sizeBand": "Large"
  },
  {
    "id": "yale-university",
    "name": "Yale University",
    "city": "New Haven",
    "state": "CT",
    "region": "Northeast",
    "usNewsRank": 4,
    "acceptanceRate": 0.047,
    "avgGpa": null,
    "satMid": 1540,
    "actMid": 34,
    "tuitionUsd": 72500,
    "setting": "Urban",
    "interests": "arts,humanities,law,science",
    "personalityFit": "creative,intellectual",
    "extracurricularFit": "theater,writing,research,activism",
    "vrTourUrl": "https://admissions.yale.edu/virtual-events",
    "cdsUrl": "https://www.collegedata.fyi/",
    "websiteUrl": "https://www.yale.edu/",
    "sizeBand": "Medium"
  },
  {
    "id": "university-of-chicago",
    "name": "University of Chicago",
    "city": "Chicago",
    "state": "IL",
    "region": "Midwest",
    "usNewsRank": 6,
    "acceptanceRate": 0.045,
    "avgGpa": 4.97,
    "satMid": 1535,
    "actMid": 35,
    "tuitionUsd": 71325,
    "setting": "Urban",
    "interests": "academics,research,campus life",
    "personalityFit": "balanced,ambitious",
    "extracurricularFit": "clubs,research,service,athletics",
    "vrTourUrl": "https://www.google.com/search?q=University%20of%20Chicago%20virtual%20tour",
    "cdsUrl": "https://www.gradgpt.com/common-data-set",
    "websiteUrl": "https://www.uchicago.edu/",
    "sizeBand": "Large"
  },
  {
    "id": "duke-university",
    "name": "Duke University",
    "city": "Durham",
    "state": "NC",
    "region": "South",
    "usNewsRank": 7,
    "acceptanceRate": 0.052,
    "avgGpa": null,
    "satMid": 1540,
    "actMid": 35,
    "tuitionUsd": 73740,
    "setting": "Suburban",
    "interests": "medicine,public policy,engineering,research",
    "personalityFit": "ambitious,leader",
    "extracurricularFit": "athletics,research,service,debate",
    "vrTourUrl": "https://admissions.duke.edu/visit/virtual-experiences/",
    "cdsUrl": "https://www.gradgpt.com/common-data-set",
    "websiteUrl": "https://www.duke.edu/",
    "sizeBand": "Medium"
  },
  {
    "id": "johns-hopkins-university",
    "name": "Johns Hopkins University",
    "city": "Baltimore",
    "state": "MD",
    "region": "Northeast",
    "usNewsRank": 7,
    "acceptanceRate": 0.061,
    "avgGpa": 3.93,
    "satMid": 1550,
    "actMid": 35,
    "tuitionUsd": 68670,
    "setting": "Urban",
    "interests": "academics,research,campus life",
    "personalityFit": "balanced,ambitious",
    "extracurricularFit": "clubs,research,service,athletics",
    "vrTourUrl": "https://www.google.com/search?q=Johns%20Hopkins%20University%20virtual%20tour",
    "cdsUrl": "https://www.collegedata.fyi/",
    "websiteUrl": "https://www.jhu.edu/",
    "sizeBand": "Large"
  },
  {
    "id": "northwestern-university",
    "name": "Northwestern University",
    "city": "Evanston",
    "state": "IL",
    "region": "Midwest",
    "usNewsRank": 7,
    "acceptanceRate": 0.077,
    "avgGpa": null,
    "satMid": 1535,
    "actMid": 35,
    "tuitionUsd": 69375,
    "setting": "Suburban",
    "interests": "journalism,engineering,business,arts",
    "personalityFit": "creative,ambitious",
    "extracurricularFit": "media,research,performance,debate",
    "vrTourUrl": "https://admissions.northwestern.edu/visit/virtual-opportunities.html",
    "cdsUrl": "https://www.gradgpt.com/common-data-set",
    "websiteUrl": "https://www.northwestern.edu/",
    "sizeBand": "Medium"
  },
  {
    "id": "university-of-pennsylvania",
    "name": "University of Pennsylvania",
    "city": "Philadelphia",
    "state": "PA",
    "region": "Northeast",
    "usNewsRank": 7,
    "acceptanceRate": 0.049,
    "avgGpa": 3.9,
    "satMid": null,
    "actMid": 35,
    "tuitionUsd": 63204,
    "setting": "Urban",
    "interests": "engineering,business,communications,science",
    "personalityFit": "balanced,outgoing",
    "extracurricularFit": "athletics,clubs,research,Greek life",
    "vrTourUrl": "https://admissions.psu.edu/visit/virtual/",
    "cdsUrl": "https://www.collegedata.fyi/",
    "websiteUrl": "https://www.upenn.edu/",
    "sizeBand": "Large"
  },
  {
    "id": "california-institute-of-technology",
    "name": "California Institute of Technology",
    "city": "Pasadena",
    "state": "CA",
    "region": "West",
    "usNewsRank": 11,
    "acceptanceRate": 0.026,
    "avgGpa": null,
    "satMid": null,
    "actMid": null,
    "tuitionUsd": null,
    "setting": "Suburban",
    "interests": "academics,research,campus life",
    "personalityFit": "balanced,ambitious",
    "extracurricularFit": "clubs,research,service,athletics",
    "vrTourUrl": "https://www.google.com/search?q=California%20Institute%20of%20Technology%20virtual%20tour",
    "cdsUrl": "https://www.gradgpt.com/common-data-set",
    "websiteUrl": "https://www.caltech.edu/",
    "sizeBand": "Large"
  },
  {
    "id": "cornell-university",
    "name": "Cornell University",
    "city": "Ithaca",
    "state": "NY",
    "region": "Northeast",
    "usNewsRank": 12,
    "acceptanceRate": 0.084,
    "avgGpa": null,
    "satMid": 1520,
    "actMid": null,
    "tuitionUsd": null,
    "setting": "College town",
    "interests": "academics,research,campus life",
    "personalityFit": "balanced,ambitious",
    "extracurricularFit": "clubs,research,service,athletics",
    "vrTourUrl": "https://www.google.com/search?q=Cornell%20University%20virtual%20tour",
    "cdsUrl": "https://www.gradgpt.com/common-data-set",
    "websiteUrl": "https://www.cornell.edu/",
    "sizeBand": "Large"
  },
  {
    "id": "brown-university",
    "name": "Brown University",
    "city": "Providence",
    "state": "RI",
    "region": "Northeast",
    "usNewsRank": 13,
    "acceptanceRate": 0.063,
    "avgGpa": null,
    "satMid": 1510,
    "actMid": null,
    "tuitionUsd": 74568,
    "setting": "Urban",
    "interests": "academics,research,campus life",
    "personalityFit": "balanced,ambitious",
    "extracurricularFit": "clubs,research,service,athletics",
    "vrTourUrl": "https://www.google.com/search?q=Brown%20University%20virtual%20tour",
    "cdsUrl": "https://www.gradgpt.com/common-data-set",
    "websiteUrl": "https://www.brown.edu/",
    "sizeBand": "Large"
  },
  {
    "id": "dartmouth-college",
    "name": "Dartmouth College",
    "city": "Hanover",
    "state": "NH",
    "region": "Northeast",
    "usNewsRank": 13,
    "acceptanceRate": 0.06,
    "avgGpa": null,
    "satMid": 1495,
    "actMid": null,
    "tuitionUsd": null,
    "setting": "College town",
    "interests": "academics,research,campus life",
    "personalityFit": "balanced,ambitious",
    "extracurricularFit": "clubs,research,service,athletics",
    "vrTourUrl": "https://www.google.com/search?q=Dartmouth%20College%20virtual%20tour",
    "cdsUrl": "https://www.gradgpt.com/common-data-set",
    "websiteUrl": "https://home.dartmouth.edu/",
    "sizeBand": "Large"
  },
  {
    "id": "columbia-university",
    "name": "Columbia University",
    "city": "New York",
    "state": "NY",
    "region": "Northeast",
    "usNewsRank": 15,
    "acceptanceRate": 0.039,
    "avgGpa": null,
    "satMid": 1535,
    "actMid": null,
    "tuitionUsd": null,
    "setting": "Urban",
    "interests": "academics,research,campus life",
    "personalityFit": "balanced,ambitious",
    "extracurricularFit": "clubs,research,service,athletics",
    "vrTourUrl": "https://www.google.com/search?q=Columbia%20University%20virtual%20tour",
    "cdsUrl": "https://www.gradgpt.com/common-data-set",
    "websiteUrl": "https://www.columbia.edu/",
    "sizeBand": "Large"
  },
  {
    "id": "university-of-california-berkeley",
    "name": "University of California, Berkeley",
    "city": "Berkeley",
    "state": "CA",
    "region": "West",
    "usNewsRank": 15,
    "acceptanceRate": 0.114,
    "avgGpa": null,
    "satMid": null,
    "actMid": null,
    "tuitionUsd": null,
    "setting": "Urban",
    "interests": "CS,engineering,social impact,research",
    "personalityFit": "activist,analytical",
    "extracurricularFit": "research,activism,entrepreneurship,clubs",
    "vrTourUrl": "https://visit.berkeley.edu/virtual-tour/",
    "cdsUrl": "https://www.gradgpt.com/common-data-set",
    "websiteUrl": "https://www.berkeley.edu/",
    "sizeBand": "Large"
  },
  {
    "id": "rice-university",
    "name": "Rice University",
    "city": "Houston",
    "state": "TX",
    "region": "South",
    "usNewsRank": 17,
    "acceptanceRate": 0.08,
    "avgGpa": null,
    "satMid": 1535,
    "actMid": null,
    "tuitionUsd": null,
    "setting": "Urban",
    "interests": "academics,research,campus life",
    "personalityFit": "balanced,ambitious",
    "extracurricularFit": "clubs,research,service,athletics",
    "vrTourUrl": "https://www.google.com/search?q=Rice%20University%20virtual%20tour",
    "cdsUrl": "https://www.gradgpt.com/common-data-set",
    "websiteUrl": "https://www.rice.edu/",
    "sizeBand": "Large"
  },
  {
    "id": "university-of-california-los-angeles",
    "name": "University of California, Los Angeles",
    "city": "Los Angeles",
    "state": "CA",
    "region": "West",
    "usNewsRank": 17,
    "acceptanceRate": 0.09,
    "avgGpa": null,
    "satMid": null,
    "actMid": null,
    "tuitionUsd": null,
    "setting": "Urban",
    "interests": "film,medicine,business,arts",
    "personalityFit": "creative,outgoing",
    "extracurricularFit": "film,athletics,performing arts,service",
    "vrTourUrl": "https://tour.ucla.edu/",
    "cdsUrl": "https://www.gradgpt.com/common-data-set",
    "websiteUrl": "https://www.ucla.edu/",
    "sizeBand": "Large"
  },
  {
    "id": "vanderbilt-university",
    "name": "Vanderbilt University",
    "city": "Nashville",
    "state": "TN",
    "region": "South",
    "usNewsRank": 17,
    "acceptanceRate": 0.054,
    "avgGpa": null,
    "satMid": 1535,
    "actMid": null,
    "tuitionUsd": null,
    "setting": "Urban",
    "interests": "academics,research,campus life",
    "personalityFit": "balanced,ambitious",
    "extracurricularFit": "clubs,research,service,athletics",
    "vrTourUrl": "https://www.google.com/search?q=Vanderbilt%20University%20virtual%20tour",
    "cdsUrl": "https://www.gradgpt.com/common-data-set",
    "websiteUrl": "https://www.vanderbilt.edu/",
    "sizeBand": "Large"
  },
  {
    "id": "carnegie-mellon-university",
    "name": "Carnegie Mellon University",
    "city": "Pittsburgh",
    "state": "PA",
    "region": "Northeast",
    "usNewsRank": 20,
    "acceptanceRate": 0.111,
    "avgGpa": 3.89,
    "satMid": 1540,
    "actMid": 35,
    "tuitionUsd": null,
    "setting": "Urban",
    "interests": "CS,engineering,drama,design",
    "personalityFit": "analytical,creative",
    "extracurricularFit": "hackathons,theater,research,design",
    "vrTourUrl": "https://www.cmu.edu/admission/visit/virtual",
    "cdsUrl": "https://www.collegedata.fyi/",
    "websiteUrl": "https://www.cmu.edu/",
    "sizeBand": "Medium"
  },
  {
    "id": "university-of-michigan-ann-arbor",
    "name": "University of Michigan, Ann Arbor",
    "city": "Ann Arbor",
    "state": "MI",
    "region": "Midwest",
    "usNewsRank": 20,
    "acceptanceRate": 0.164,
    "avgGpa": null,
    "satMid": 1450,
    "actMid": null,
    "tuitionUsd": null,
    "setting": "College town",
    "interests": "business,engineering,public policy",
    "personalityFit": "balanced,leader",
    "extracurricularFit": "athletics,research,Greek life,clubs",
    "vrTourUrl": "https://campusinfo.umich.edu/tour",
    "cdsUrl": "https://www.gradgpt.com/common-data-set",
    "websiteUrl": "https://umich.edu/",
    "sizeBand": "Large"
  },
  {
    "id": "university-of-notre-dame",
    "name": "University of Notre Dame",
    "city": "Notre Dame",
    "state": "IN",
    "region": "Midwest",
    "usNewsRank": 20,
    "acceptanceRate": 0.094,
    "avgGpa": null,
    "satMid": 1500,
    "actMid": null,
    "tuitionUsd": null,
    "setting": "Suburban",
    "interests": "academics,research,campus life",
    "personalityFit": "balanced,ambitious",
    "extracurricularFit": "clubs,research,service,athletics",
    "vrTourUrl": "https://www.google.com/search?q=University%20of%20Notre%20Dame%20virtual%20tour",
    "cdsUrl": "https://www.gradgpt.com/common-data-set",
    "websiteUrl": "https://www.nd.edu/",
    "sizeBand": "Large"
  },
  {
    "id": "washington-university-in-st-louis",
    "name": "Washington University in St. Louis",
    "city": "St. Louis",
    "state": "MO",
    "region": "Midwest",
    "usNewsRank": 20,
    "acceptanceRate": 0.119,
    "avgGpa": null,
    "satMid": 1525,
    "actMid": null,
    "tuitionUsd": null,
    "setting": "Suburban",
    "interests": "CS,engineering,environmental science,medicine",
    "personalityFit": "analytical,collaborative",
    "extracurricularFit": "research,outdoors,tech clubs,service",
    "vrTourUrl": "https://www.washington.edu/visit/virtual-tour/",
    "cdsUrl": "https://www.gradgpt.com/common-data-set",
    "websiteUrl": "https://wustl.edu/",
    "sizeBand": "Large"
  },
  {
    "id": "emory-university",
    "name": "Emory University",
    "city": "Atlanta",
    "state": "GA",
    "region": "South",
    "usNewsRank": 24,
    "acceptanceRate": 0.103,
    "avgGpa": null,
    "satMid": 1510,
    "actMid": null,
    "tuitionUsd": null,
    "setting": "Suburban",
    "interests": "academics,research,campus life",
    "personalityFit": "balanced,ambitious",
    "extracurricularFit": "clubs,research,service,athletics",
    "vrTourUrl": "https://www.google.com/search?q=Emory%20University%20virtual%20tour",
    "cdsUrl": "https://www.gradgpt.com/common-data-set",
    "websiteUrl": "https://www.emory.edu/",
    "sizeBand": "Large"
  },
  {
    "id": "georgetown-university",
    "name": "Georgetown University",
    "city": "Washington",
    "state": "DC",
    "region": "Northeast",
    "usNewsRank": 24,
    "acceptanceRate": null,
    "avgGpa": null,
    "satMid": null,
    "actMid": null,
    "tuitionUsd": null,
    "setting": "Urban",
    "interests": "academics,research,campus life",
    "personalityFit": "balanced,ambitious",
    "extracurricularFit": "clubs,research,service,athletics",
    "vrTourUrl": "https://www.google.com/search?q=Georgetown%20University%20virtual%20tour",
    "cdsUrl": "https://www.collegedata.fyi/",
    "websiteUrl": "https://www.georgetown.edu/",
    "sizeBand": "Large"
  },
  {
    "id": "university-of-north-carolina-at-chapel-hill",
    "name": "University of North Carolina at Chapel Hill",
    "city": "Chapel Hill",
    "state": "NC",
    "region": "South",
    "usNewsRank": 26,
    "acceptanceRate": 0.167,
    "avgGpa": null,
    "satMid": 1465,
    "actMid": null,
    "tuitionUsd": null,
    "setting": "College town",
    "interests": "public health,journalism,business,research",
    "personalityFit": "balanced,outgoing",
    "extracurricularFit": "athletics,service,research,media",
    "vrTourUrl": "https://admissions.unc.edu/visit/virtual-visit/",
    "cdsUrl": "https://www.gradgpt.com/common-data-set",
    "websiteUrl": "https://www.unc.edu/",
    "sizeBand": "Large"
  },
  {
    "id": "university-of-virginia",
    "name": "University of Virginia",
    "city": "Charlottesville",
    "state": "VA",
    "region": "South",
    "usNewsRank": 26,
    "acceptanceRate": 0.156,
    "avgGpa": null,
    "satMid": 1460,
    "actMid": null,
    "tuitionUsd": null,
    "setting": "College town",
    "interests": "liberal arts,business,law,public service",
    "personalityFit": "traditional,leader",
    "extracurricularFit": "honor societies,service,athletics,debate",
    "vrTourUrl": "https://admission.virginia.edu/visit/virtual-events",
    "cdsUrl": "https://www.gradgpt.com/common-data-set",
    "websiteUrl": "https://www.virginia.edu/",
    "sizeBand": "Large"
  },
  {
    "id": "university-of-southern-california",
    "name": "University of Southern California",
    "city": "Los Angeles",
    "state": "CA",
    "region": "West",
    "usNewsRank": 28,
    "acceptanceRate": 0.112,
    "avgGpa": null,
    "satMid": 1505,
    "actMid": null,
    "tuitionUsd": null,
    "setting": "Urban",
    "interests": "film,business,engineering,communications",
    "personalityFit": "creative,outgoing",
    "extracurricularFit": "film,athletics,entrepreneurship,arts",
    "vrTourUrl": "https://admission.usc.edu/learn/visit-usc/virtual-tour/",
    "cdsUrl": "https://www.gradgpt.com/common-data-set",
    "websiteUrl": "https://www.usc.edu/",
    "sizeBand": "Large"
  },
  {
    "id": "university-of-california-san-diego",
    "name": "University of California, San Diego",
    "city": "La Jolla",
    "state": "CA",
    "region": "West",
    "usNewsRank": 29,
    "acceptanceRate": 0.286,
    "avgGpa": null,
    "satMid": null,
    "actMid": null,
    "tuitionUsd": null,
    "setting": "Suburban",
    "interests": "academics,research,campus life",
    "personalityFit": "balanced,ambitious",
    "extracurricularFit": "clubs,research,service,athletics",
    "vrTourUrl": "https://www.google.com/search?q=University%20of%20California%2C%20San%20Diego%20virtual%20tour",
    "cdsUrl": "https://www.gradgpt.com/common-data-set",
    "websiteUrl": "https://www.ucsd.edu/",
    "sizeBand": "Large"
  },
  {
    "id": "university-of-florida",
    "name": "University of Florida",
    "city": "Gainesville",
    "state": "FL",
    "region": "South",
    "usNewsRank": 30,
    "acceptanceRate": 0.233,
    "avgGpa": null,
    "satMid": 1400,
    "actMid": null,
    "tuitionUsd": null,
    "setting": "College town",
    "interests": "pre-med,business,engineering,sciences",
    "personalityFit": "ambitious,outgoing",
    "extracurricularFit": "athletics,research,Greek life,service",
    "vrTourUrl": "https://admissions.ufl.edu/visit/virtual-tour/",
    "cdsUrl": "https://www.gradgpt.com/common-data-set",
    "websiteUrl": "https://www.ufl.edu/",
    "sizeBand": "Large"
  },
  {
    "id": "university-of-texas-at-austin",
    "name": "University of Texas at Austin",
    "city": "Austin",
    "state": "TX",
    "region": "South",
    "usNewsRank": 30,
    "acceptanceRate": 0.222,
    "avgGpa": null,
    "satMid": null,
    "actMid": null,
    "tuitionUsd": null,
    "setting": "Urban",
    "interests": "business,engineering,CS,communications",
    "personalityFit": "entrepreneurial,outgoing",
    "extracurricularFit": "startups,athletics,music,clubs",
    "vrTourUrl": "https://visit.utexas.edu/virtual-tour/",
    "cdsUrl": "https://www.gradgpt.com/common-data-set",
    "websiteUrl": "https://www.utexas.edu/",
    "sizeBand": "Large"
  },
  {
    "id": "georgia-institute-of-technology",
    "name": "Georgia Institute of Technology",
    "city": "Atlanta",
    "state": "GA",
    "region": "South",
    "usNewsRank": 32,
    "acceptanceRate": 0.133,
    "avgGpa": null,
    "satMid": 1450,
    "actMid": null,
    "tuitionUsd": null,
    "setting": "Urban",
    "interests": "engineering,CS,computing,innovation",
    "personalityFit": "analytical,innovator",
    "extracurricularFit": "hackathons,research,robotics,STEM clubs",
    "vrTourUrl": "https://admission.gatech.edu/visit/virtual-visit",
    "cdsUrl": "https://www.gradgpt.com/common-data-set",
    "websiteUrl": "https://www.gatech.edu/",
    "sizeBand": "Large"
  },
  {
    "id": "new-york-university",
    "name": "New York University",
    "city": "New York",
    "state": "NY",
    "region": "Northeast",
    "usNewsRank": 32,
    "acceptanceRate": 0.091,
    "avgGpa": null,
    "satMid": 1515,
    "actMid": null,
    "tuitionUsd": null,
    "setting": "Urban",
    "interests": "arts,business,film,international studies",
    "personalityFit": "creative,cosmopolitan",
    "extracurricularFit": "arts,internships,media,entrepreneurship",
    "vrTourUrl": "https://www.nyu.edu/admissions/undergraduate-admissions/visit/virtual-tour.html",
    "cdsUrl": "https://www.gradgpt.com/common-data-set",
    "websiteUrl": "https://www.nyu.edu/",
    "sizeBand": "Large"
  },
  {
    "id": "university-of-california-davis",
    "name": "University of California, Davis",
    "city": "Davis",
    "state": "CA",
    "region": "West",
    "usNewsRank": 32,
    "acceptanceRate": 0.444,
    "avgGpa": null,
    "satMid": null,
    "actMid": null,
    "tuitionUsd": null,
    "setting": "College town",
    "interests": "academics,research,campus life",
    "personalityFit": "balanced,ambitious",
    "extracurricularFit": "clubs,research,service,athletics",
    "vrTourUrl": "https://www.google.com/search?q=University%20of%20California%2C%20Davis%20virtual%20tour",
    "cdsUrl": "https://www.gradgpt.com/common-data-set",
    "websiteUrl": "https://www.ucdavis.edu/",
    "sizeBand": "Large"
  },
  {
    "id": "university-of-california-irvine",
    "name": "University of California, Irvine",
    "city": "Irvine",
    "state": "CA",
    "region": "West",
    "usNewsRank": 32,
    "acceptanceRate": 0.288,
    "avgGpa": null,
    "satMid": null,
    "actMid": null,
    "tuitionUsd": null,
    "setting": "Suburban",
    "interests": "academics,research,campus life",
    "personalityFit": "balanced,ambitious",
    "extracurricularFit": "clubs,research,service,athletics",
    "vrTourUrl": "https://www.google.com/search?q=University%20of%20California%2C%20Irvine%20virtual%20tour",
    "cdsUrl": "https://www.gradgpt.com/common-data-set",
    "websiteUrl": "https://www.uci.edu/",
    "sizeBand": "Large"
  },
  {
    "id": "boston-college",
    "name": "Boston College",
    "city": "Chestnut Hill",
    "state": "MA",
    "region": "Northeast",
    "usNewsRank": 36,
    "acceptanceRate": 0.162,
    "avgGpa": null,
    "satMid": 1490,
    "actMid": 34,
    "tuitionUsd": 72180,
    "setting": "Suburban",
    "interests": "communications,business,international relations,pre-med",
    "personalityFit": "ambitious,cosmopolitan",
    "extracurricularFit": "internships,research,media,service",
    "vrTourUrl": "https://www.bu.edu/admissions/visit-bu/virtual-tour/",
    "cdsUrl": "https://www.gradgpt.com/common-data-set",
    "websiteUrl": "https://www.bc.edu/",
    "sizeBand": "Large"
  },
  {
    "id": "tufts-university",
    "name": "Tufts University",
    "city": "Medford",
    "state": "MA",
    "region": "Northeast",
    "usNewsRank": 36,
    "acceptanceRate": 0.108,
    "avgGpa": null,
    "satMid": 1490,
    "actMid": null,
    "tuitionUsd": null,
    "setting": "Suburban",
    "interests": "academics,research,campus life",
    "personalityFit": "balanced,ambitious",
    "extracurricularFit": "clubs,research,service,athletics",
    "vrTourUrl": "https://www.google.com/search?q=Tufts%20University%20virtual%20tour",
    "cdsUrl": "https://www.gradgpt.com/common-data-set",
    "websiteUrl": "https://www.tufts.edu/",
    "sizeBand": "Large"
  },
  {
    "id": "university-of-illinois-urbana-champaign",
    "name": "University of Illinois Urbana-Champaign",
    "city": "Champaign",
    "state": "IL",
    "region": "Midwest",
    "usNewsRank": 36,
    "acceptanceRate": 0.366,
    "avgGpa": null,
    "satMid": 1455,
    "actMid": null,
    "tuitionUsd": null,
    "setting": "College town",
    "interests": "CS,engineering,business,research",
    "personalityFit": "analytical,collaborative",
    "extracurricularFit": "hackathons,research,clubs,athletics",
    "vrTourUrl": "https://admissions.illinois.edu/visit/virtual-tour",
    "cdsUrl": "https://www.gradgpt.com/common-data-set",
    "websiteUrl": "https://illinois.edu/",
    "sizeBand": "Large"
  },
  {
    "id": "university-of-wisconsin-madison",
    "name": "University of Wisconsin-Madison",
    "city": "Madison",
    "state": "WI",
    "region": "Midwest",
    "usNewsRank": 36,
    "acceptanceRate": 0.408,
    "avgGpa": null,
    "satMid": 1445,
    "actMid": null,
    "tuitionUsd": null,
    "setting": "College town",
    "interests": "research,business,agriculture,engineering",
    "personalityFit": "balanced,outgoing",
    "extracurricularFit": "athletics,research,outdoors,clubs",
    "vrTourUrl": "https://www.visit.wisc.edu/virtual-tour/",
    "cdsUrl": "https://www.gradgpt.com/common-data-set",
    "websiteUrl": "https://www.wisc.edu/",
    "sizeBand": "Large"
  },
  {
    "id": "university-of-california-santa-barbara",
    "name": "University of California, Santa Barbara",
    "city": "Santa Barbara",
    "state": "CA",
    "region": "West",
    "usNewsRank": 40,
    "acceptanceRate": 0.382,
    "avgGpa": null,
    "satMid": null,
    "actMid": null,
    "tuitionUsd": null,
    "setting": "Suburban",
    "interests": "academics,research,campus life",
    "personalityFit": "balanced,ambitious",
    "extracurricularFit": "clubs,research,service,athletics",
    "vrTourUrl": "https://www.google.com/search?q=University%20of%20California%2C%20Santa%20Barbara%20virtual%20tour",
    "cdsUrl": "https://www.gradgpt.com/common-data-set",
    "websiteUrl": "https://www.ucsb.edu/",
    "sizeBand": "Large"
  },
  {
    "id": "ohio-state-university",
    "name": "Ohio State University",
    "city": "Columbus",
    "state": "OH",
    "region": "Midwest",
    "usNewsRank": 41,
    "acceptanceRate": 0.606,
    "avgGpa": null,
    "satMid": 1355,
    "actMid": null,
    "tuitionUsd": null,
    "setting": "Urban",
    "interests": "business,engineering,health,agriculture",
    "personalityFit": "outgoing,leader",
    "extracurricularFit": "athletics,Greek life,research,clubs",
    "vrTourUrl": "https://visit.osu.edu/virtual-tour",
    "cdsUrl": "https://www.gradgpt.com/common-data-set",
    "websiteUrl": "https://www.osu.edu/",
    "sizeBand": "Large"
  },
  {
    "id": "boston-university",
    "name": "Boston University",
    "city": "Boston",
    "state": "MA",
    "region": "Northeast",
    "usNewsRank": 42,
    "acceptanceRate": 0.128,
    "avgGpa": 3.86,
    "satMid": 1465,
    "actMid": 34,
    "tuitionUsd": 69870,
    "setting": "Urban",
    "interests": "communications,business,international relations,pre-med",
    "personalityFit": "ambitious,cosmopolitan",
    "extracurricularFit": "internships,research,media,service",
    "vrTourUrl": "https://www.bu.edu/admissions/visit-bu/virtual-tour/",
    "cdsUrl": "https://www.gradgpt.com/common-data-set",
    "websiteUrl": "https://www.bu.edu/",
    "sizeBand": "Large"
  },
  {
    "id": "rutgers-university-new-brunswick",
    "name": "Rutgers University-New Brunswick",
    "city": "New Brunswick",
    "state": "NJ",
    "region": "Northeast",
    "usNewsRank": 42,
    "acceptanceRate": 0.653,
    "avgGpa": null,
    "satMid": 1375,
    "actMid": null,
    "tuitionUsd": null,
    "setting": "Urban",
    "interests": "academics,research,campus life",
    "personalityFit": "balanced,ambitious",
    "extracurricularFit": "clubs,research,service,athletics",
    "vrTourUrl": "https://www.google.com/search?q=Rutgers%20University-New%20Brunswick%20virtual%20tour",
    "cdsUrl": "https://www.gradgpt.com/common-data-set",
    "websiteUrl": "https://www.rutgers.edu/",
    "sizeBand": "Large"
  },
  {
    "id": "university-of-maryland-college-park",
    "name": "University of Maryland, College Park",
    "city": "College Park",
    "state": "MD",
    "region": "Northeast",
    "usNewsRank": 42,
    "acceptanceRate": 0.45,
    "avgGpa": null,
    "satMid": 1465,
    "actMid": null,
    "tuitionUsd": null,
    "setting": "Suburban",
    "interests": "academics,research,campus life",
    "personalityFit": "balanced,ambitious",
    "extracurricularFit": "clubs,research,service,athletics",
    "vrTourUrl": "https://www.google.com/search?q=University%20of%20Maryland%2C%20College%20Park%20virtual%20tour",
    "cdsUrl": "https://www.gradgpt.com/common-data-set",
    "websiteUrl": "https://www.umd.edu/",
    "sizeBand": "Large"
  },
  {
    "id": "university-of-washington",
    "name": "University of Washington",
    "city": "Seattle",
    "state": "WA",
    "region": "West",
    "usNewsRank": 42,
    "acceptanceRate": 0.417,
    "avgGpa": null,
    "satMid": 1411,
    "actMid": null,
    "tuitionUsd": null,
    "setting": "Urban",
    "interests": "CS,engineering,environmental science,medicine",
    "personalityFit": "analytical,collaborative",
    "extracurricularFit": "research,outdoors,tech clubs,service",
    "vrTourUrl": "https://www.washington.edu/visit/virtual-tour/",
    "cdsUrl": "https://www.gradgpt.com/common-data-set",
    "websiteUrl": "https://www.washington.edu/",
    "sizeBand": "Large"
  },
  {
    "id": "lehigh-university",
    "name": "Lehigh University",
    "city": "Bethlehem",
    "state": "PA",
    "region": "Northeast",
    "usNewsRank": 46,
    "acceptanceRate": null,
    "avgGpa": null,
    "satMid": null,
    "actMid": null,
    "tuitionUsd": null,
    "setting": "Suburban",
    "interests": "academics,research,campus life",
    "personalityFit": "balanced,ambitious",
    "extracurricularFit": "clubs,research,service,athletics",
    "vrTourUrl": "https://www.google.com/search?q=Lehigh%20University%20virtual%20tour",
    "cdsUrl": "https://www.collegedata.fyi/",
    "websiteUrl": "https://www.lehigh.edu/",
    "sizeBand": "Large"
  },
  {
    "id": "northeastern-university",
    "name": "Northeastern University",
    "city": "Boston",
    "state": "MA",
    "region": "Northeast",
    "usNewsRank": 46,
    "acceptanceRate": null,
    "avgGpa": null,
    "satMid": null,
    "actMid": null,
    "tuitionUsd": null,
    "setting": "Urban",
    "interests": "academics,research,campus life",
    "personalityFit": "balanced,ambitious",
    "extracurricularFit": "clubs,research,service,athletics",
    "vrTourUrl": "https://www.google.com/search?q=Northeastern%20University%20virtual%20tour",
    "cdsUrl": "https://www.collegedata.fyi/",
    "websiteUrl": "https://www.northeastern.edu/",
    "sizeBand": "Large"
  },
  {
    "id": "purdue-university",
    "name": "Purdue University",
    "city": "West Lafayette",
    "state": "IN",
    "region": "Midwest",
    "usNewsRank": 46,
    "acceptanceRate": 0.434,
    "avgGpa": null,
    "satMid": 1345,
    "actMid": null,
    "tuitionUsd": null,
    "setting": "College town",
    "interests": "engineering,aviation,agriculture,CS",
    "personalityFit": "analytical,practical",
    "extracurricularFit": "STEM clubs,research,athletics,maker",
    "vrTourUrl": "https://www.purdue.edu/visit/virtual-tour/",
    "cdsUrl": "https://www.gradgpt.com/common-data-set",
    "websiteUrl": "https://www.purdue.edu/",
    "sizeBand": "Large"
  },
  {
    "id": "university-of-georgia",
    "name": "University of Georgia",
    "city": "Athens",
    "state": "GA",
    "region": "South",
    "usNewsRank": 46,
    "acceptanceRate": 0.343,
    "avgGpa": null,
    "satMid": 1335,
    "actMid": null,
    "tuitionUsd": null,
    "setting": "College town",
    "interests": "engineering,CS,computing,innovation",
    "personalityFit": "analytical,innovator",
    "extracurricularFit": "hackathons,research,robotics,STEM clubs",
    "vrTourUrl": "https://admission.gatech.edu/visit/virtual-visit",
    "cdsUrl": "https://www.gradgpt.com/common-data-set",
    "websiteUrl": "https://www.uga.edu/",
    "sizeBand": "Large"
  },
  {
    "id": "university-of-rochester",
    "name": "University of Rochester",
    "city": "Rochester",
    "state": "NY",
    "region": "Northeast",
    "usNewsRank": 46,
    "acceptanceRate": 0.419,
    "avgGpa": null,
    "satMid": 1455,
    "actMid": null,
    "tuitionUsd": null,
    "setting": "Suburban",
    "interests": "academics,research,campus life",
    "personalityFit": "balanced,ambitious",
    "extracurricularFit": "clubs,research,service,athletics",
    "vrTourUrl": "https://www.google.com/search?q=University%20of%20Rochester%20virtual%20tour",
    "cdsUrl": "https://www.gradgpt.com/common-data-set",
    "websiteUrl": "https://www.rochester.edu/",
    "sizeBand": "Large"
  },
  {
    "id": "case-western-reserve-university",
    "name": "Case Western Reserve University",
    "city": "Cleveland",
    "state": "OH",
    "region": "Midwest",
    "usNewsRank": 51,
    "acceptanceRate": 0.353,
    "avgGpa": null,
    "satMid": 1485,
    "actMid": null,
    "tuitionUsd": null,
    "setting": "Urban",
    "interests": "academics,research,campus life",
    "personalityFit": "balanced,ambitious",
    "extracurricularFit": "clubs,research,service,athletics",
    "vrTourUrl": "https://www.google.com/search?q=Case%20Western%20Reserve%20University%20virtual%20tour",
    "cdsUrl": "https://www.gradgpt.com/common-data-set",
    "websiteUrl": "https://case.edu/",
    "sizeBand": "Large"
  },
  {
    "id": "florida-state-university",
    "name": "Florida State University",
    "city": "Tallahassee",
    "state": "FL",
    "region": "South",
    "usNewsRank": 51,
    "acceptanceRate": 0.238,
    "avgGpa": null,
    "satMid": 1355,
    "actMid": null,
    "tuitionUsd": null,
    "setting": "College town",
    "interests": "pre-med,business,engineering,sciences",
    "personalityFit": "ambitious,outgoing",
    "extracurricularFit": "athletics,research,Greek life,service",
    "vrTourUrl": "https://admissions.ufl.edu/visit/virtual-tour/",
    "cdsUrl": "https://www.gradgpt.com/common-data-set",
    "websiteUrl": "https://www.fsu.edu/",
    "sizeBand": "Large"
  },
  {
    "id": "texas-a-and-m-university",
    "name": "Texas A&M University",
    "city": "College Station",
    "state": "TX",
    "region": "South",
    "usNewsRank": 51,
    "acceptanceRate": 0.517,
    "avgGpa": null,
    "satMid": 1275,
    "actMid": null,
    "tuitionUsd": null,
    "setting": "College town",
    "interests": "academics,research,campus life",
    "personalityFit": "balanced,ambitious",
    "extracurricularFit": "clubs,research,service,athletics",
    "vrTourUrl": "https://www.google.com/search?q=Texas%20A%26M%20University%20virtual%20tour",
    "cdsUrl": "https://www.gradgpt.com/common-data-set",
    "websiteUrl": "https://www.tamu.edu/",
    "sizeBand": "Large"
  },
  {
    "id": "virginia-tech",
    "name": "Virginia Tech",
    "city": "Blacksburg",
    "state": "VA",
    "region": "South",
    "usNewsRank": 51,
    "acceptanceRate": 0.546,
    "avgGpa": null,
    "satMid": 1365,
    "actMid": null,
    "tuitionUsd": null,
    "setting": "College town",
    "interests": "liberal arts,business,law,public service",
    "personalityFit": "traditional,leader",
    "extracurricularFit": "honor societies,service,athletics,debate",
    "vrTourUrl": "https://admission.virginia.edu/visit/virtual-events",
    "cdsUrl": "https://www.gradgpt.com/common-data-set",
    "websiteUrl": "https://www.vt.edu/",
    "sizeBand": "Large"
  },
  {
    "id": "wake-forest-university",
    "name": "Wake Forest University",
    "city": "Winston-Salem",
    "state": "NC",
    "region": "South",
    "usNewsRank": 51,
    "acceptanceRate": null,
    "avgGpa": null,
    "satMid": null,
    "actMid": null,
    "tuitionUsd": null,
    "setting": "Suburban",
    "interests": "academics,research,campus life",
    "personalityFit": "balanced,ambitious",
    "extracurricularFit": "clubs,research,service,athletics",
    "vrTourUrl": "https://www.google.com/search?q=Wake%20Forest%20University%20virtual%20tour",
    "cdsUrl": "https://www.collegedata.fyi/",
    "websiteUrl": "https://www.wfu.edu/",
    "sizeBand": "Large"
  },
  {
    "id": "william-and-mary",
    "name": "William & Mary",
    "city": "Williamsburg",
    "state": "VA",
    "region": "South",
    "usNewsRank": 51,
    "acceptanceRate": null,
    "avgGpa": null,
    "satMid": null,
    "actMid": null,
    "tuitionUsd": null,
    "setting": "College town",
    "interests": "academics,research,campus life",
    "personalityFit": "balanced,ambitious",
    "extracurricularFit": "clubs,research,service,athletics",
    "vrTourUrl": "https://www.google.com/search?q=William%20%26%20Mary%20virtual%20tour",
    "cdsUrl": "https://www.collegedata.fyi/",
    "websiteUrl": "https://www.wm.edu/",
    "sizeBand": "Large"
  },
  {
    "id": "university-of-california-merced",
    "name": "University of California, Merced",
    "city": "Merced",
    "state": "CA",
    "region": "West",
    "usNewsRank": 57,
    "acceptanceRate": null,
    "avgGpa": null,
    "satMid": null,
    "actMid": null,
    "tuitionUsd": null,
    "setting": "Suburban",
    "interests": "academics,research,campus life",
    "personalityFit": "balanced,ambitious",
    "extracurricularFit": "clubs,research,service,athletics",
    "vrTourUrl": "https://www.google.com/search?q=University%20of%20California%2C%20Merced%20virtual%20tour",
    "cdsUrl": "https://www.collegedata.fyi/",
    "websiteUrl": "https://www.ucmerced.edu/",
    "sizeBand": "Large"
  },
  {
    "id": "villanova-university",
    "name": "Villanova University",
    "city": "Villanova",
    "state": "PA",
    "region": "Northeast",
    "usNewsRank": 57,
    "acceptanceRate": null,
    "avgGpa": null,
    "satMid": null,
    "actMid": null,
    "tuitionUsd": null,
    "setting": "Suburban",
    "interests": "academics,research,campus life",
    "personalityFit": "balanced,ambitious",
    "extracurricularFit": "clubs,research,service,athletics",
    "vrTourUrl": "https://www.google.com/search?q=Villanova%20University%20virtual%20tour",
    "cdsUrl": "https://www.collegedata.fyi/",
    "websiteUrl": "https://www1.villanova.edu/",
    "sizeBand": "Large"
  },
  {
    "id": "george-washington-university",
    "name": "George Washington University",
    "city": "Washington",
    "state": "DC",
    "region": "Northeast",
    "usNewsRank": 59,
    "acceptanceRate": 0.471,
    "avgGpa": null,
    "satMid": 1380,
    "actMid": null,
    "tuitionUsd": null,
    "setting": "Urban",
    "interests": "CS,engineering,environmental science,medicine",
    "personalityFit": "analytical,collaborative",
    "extracurricularFit": "research,outdoors,tech clubs,service",
    "vrTourUrl": "https://www.washington.edu/visit/virtual-tour/",
    "cdsUrl": "https://www.gradgpt.com/common-data-set",
    "websiteUrl": "https://www.gwu.edu/",
    "sizeBand": "Large"
  },
  {
    "id": "pennsylvania-state-university",
    "name": "Pennsylvania State University",
    "city": "University Park",
    "state": "PA",
    "region": "Northeast",
    "usNewsRank": 59,
    "acceptanceRate": 0.553,
    "avgGpa": 3.67,
    "satMid": 1345,
    "actMid": 30,
    "tuitionUsd": 44574,
    "setting": "College town",
    "interests": "engineering,business,communications,science",
    "personalityFit": "balanced,outgoing",
    "extracurricularFit": "athletics,clubs,research,Greek life",
    "vrTourUrl": "https://admissions.psu.edu/visit/virtual/",
    "cdsUrl": "https://www.gradgpt.com/common-data-set",
    "websiteUrl": "https://www.psu.edu/",
    "sizeBand": "Large"
  },
  {
    "id": "santa-clara-university",
    "name": "Santa Clara University",
    "city": "Santa Clara",
    "state": "CA",
    "region": "West",
    "usNewsRank": 59,
    "acceptanceRate": null,
    "avgGpa": null,
    "satMid": null,
    "actMid": null,
    "tuitionUsd": null,
    "setting": "Suburban",
    "interests": "academics,research,campus life",
    "personalityFit": "balanced,ambitious",
    "extracurricularFit": "clubs,research,service,athletics",
    "vrTourUrl": "https://www.google.com/search?q=Santa%20Clara%20University%20virtual%20tour",
    "cdsUrl": "https://www.collegedata.fyi/",
    "websiteUrl": "https://www.scu.edu/",
    "sizeBand": "Large"
  },
  {
    "id": "stony-brook-university",
    "name": "Stony Brook University",
    "city": "Stony Brook",
    "state": "NY",
    "region": "Northeast",
    "usNewsRank": 59,
    "acceptanceRate": 0.482,
    "avgGpa": null,
    "satMid": 1410,
    "actMid": null,
    "tuitionUsd": null,
    "setting": "Suburban",
    "interests": "academics,research,campus life",
    "personalityFit": "balanced,ambitious",
    "extracurricularFit": "clubs,research,service,athletics",
    "vrTourUrl": "https://www.google.com/search?q=Stony%20Brook%20University%20virtual%20tour",
    "cdsUrl": "https://www.gradgpt.com/common-data-set",
    "websiteUrl": "https://www.stonybrook.edu/",
    "sizeBand": "Large"
  },
  {
    "id": "university-of-minnesota-twin-cities",
    "name": "University of Minnesota Twin Cities",
    "city": "Minneapolis",
    "state": "MN",
    "region": "Midwest",
    "usNewsRank": 59,
    "acceptanceRate": 0.789,
    "avgGpa": null,
    "satMid": 1385,
    "actMid": null,
    "tuitionUsd": null,
    "setting": "Urban",
    "interests": "academics,research,campus life",
    "personalityFit": "balanced,ambitious",
    "extracurricularFit": "clubs,research,service,athletics",
    "vrTourUrl": "https://www.google.com/search?q=University%20of%20Minnesota%20Twin%20Cities%20virtual%20tour",
    "cdsUrl": "https://www.gradgpt.com/common-data-set",
    "websiteUrl": "https://twin-cities.umn.edu/",
    "sizeBand": "Large"
  },
  {
    "id": "michigan-state-university",
    "name": "Michigan State University",
    "city": "East Lansing",
    "state": "MI",
    "region": "Midwest",
    "usNewsRank": 64,
    "acceptanceRate": 0.832,
    "avgGpa": null,
    "satMid": 1205,
    "actMid": null,
    "tuitionUsd": null,
    "setting": "College town",
    "interests": "business,engineering,public policy",
    "personalityFit": "balanced,leader",
    "extracurricularFit": "athletics,research,Greek life,clubs",
    "vrTourUrl": "https://campusinfo.umich.edu/tour",
    "cdsUrl": "https://www.gradgpt.com/common-data-set",
    "websiteUrl": "https://msu.edu/",
    "sizeBand": "Large"
  },
  {
    "id": "north-carolina-state-university",
    "name": "North Carolina State University",
    "city": "Raleigh",
    "state": "NC",
    "region": "South",
    "usNewsRank": 64,
    "acceptanceRate": 0.395,
    "avgGpa": null,
    "satMid": 1375,
    "actMid": null,
    "tuitionUsd": null,
    "setting": "Urban",
    "interests": "academics,research,campus life",
    "personalityFit": "balanced,ambitious",
    "extracurricularFit": "clubs,research,service,athletics",
    "vrTourUrl": "https://www.google.com/search?q=North%20Carolina%20State%20University%20virtual%20tour",
    "cdsUrl": "https://www.gradgpt.com/common-data-set",
    "websiteUrl": "https://www.ncsu.edu/",
    "sizeBand": "Large"
  },
  {
    "id": "rensselaer-polytechnic-institute",
    "name": "Rensselaer Polytechnic Institute",
    "city": "Troy",
    "state": "NY",
    "region": "Northeast",
    "usNewsRank": 64,
    "acceptanceRate": null,
    "avgGpa": null,
    "satMid": null,
    "actMid": null,
    "tuitionUsd": null,
    "setting": "Suburban",
    "interests": "academics,research,campus life",
    "personalityFit": "balanced,ambitious",
    "extracurricularFit": "clubs,research,service,athletics",
    "vrTourUrl": "https://www.google.com/search?q=Rensselaer%20Polytechnic%20Institute%20virtual%20tour",
    "cdsUrl": "https://www.collegedata.fyi/",
    "websiteUrl": "https://www.rpi.edu/",
    "sizeBand": "Large"
  },
  {
    "id": "university-of-massachusetts-amherst",
    "name": "University of Massachusetts Amherst",
    "city": "Amherst",
    "state": "MA",
    "region": "Northeast",
    "usNewsRank": 64,
    "acceptanceRate": 0.58,
    "avgGpa": null,
    "satMid": 1385,
    "actMid": null,
    "tuitionUsd": null,
    "setting": "College town",
    "interests": "academics,research,campus life",
    "personalityFit": "balanced,ambitious",
    "extracurricularFit": "clubs,research,service,athletics",
    "vrTourUrl": "https://www.google.com/search?q=University%20of%20Massachusetts%20Amherst%20virtual%20tour",
    "cdsUrl": "https://www.gradgpt.com/common-data-set",
    "websiteUrl": "https://www.umass.edu/",
    "sizeBand": "Large"
  },
  {
    "id": "university-of-miami",
    "name": "University of Miami",
    "city": "Coral Gables",
    "state": "FL",
    "region": "South",
    "usNewsRank": 64,
    "acceptanceRate": 0.176,
    "avgGpa": null,
    "satMid": 1400,
    "actMid": null,
    "tuitionUsd": null,
    "setting": "Suburban",
    "interests": "marine science,business,communications,music",
    "personalityFit": "outgoing,creative",
    "extracurricularFit": "athletics,music,research,service",
    "vrTourUrl": "https://admissions.miami.edu/undergraduate/visit/virtual-tour/index.html",
    "cdsUrl": "https://www.gradgpt.com/common-data-set",
    "websiteUrl": "https://www.miami.edu/",
    "sizeBand": "Medium"
  },
  {
    "id": "brandeis-university",
    "name": "Brandeis University",
    "city": "Waltham",
    "state": "MA",
    "region": "Northeast",
    "usNewsRank": 69,
    "acceptanceRate": null,
    "avgGpa": null,
    "satMid": null,
    "actMid": null,
    "tuitionUsd": null,
    "setting": "Suburban",
    "interests": "academics,research,campus life",
    "personalityFit": "balanced,ambitious",
    "extracurricularFit": "clubs,research,service,athletics",
    "vrTourUrl": "https://www.google.com/search?q=Brandeis%20University%20virtual%20tour",
    "cdsUrl": "https://www.collegedata.fyi/",
    "websiteUrl": "https://www.brandeis.edu/",
    "sizeBand": "Large"
  },
  {
    "id": "tulane-university",
    "name": "Tulane University",
    "city": "New Orleans",
    "state": "LA",
    "region": "South",
    "usNewsRank": 69,
    "acceptanceRate": null,
    "avgGpa": null,
    "satMid": null,
    "actMid": null,
    "tuitionUsd": null,
    "setting": "Urban",
    "interests": "academics,research,campus life",
    "personalityFit": "balanced,ambitious",
    "extracurricularFit": "clubs,research,service,athletics",
    "vrTourUrl": "https://www.google.com/search?q=Tulane%20University%20virtual%20tour",
    "cdsUrl": "https://www.gradgpt.com/common-data-set",
    "websiteUrl": "https://tulane.edu/",
    "sizeBand": "Large"
  },
  {
    "id": "university-of-connecticut",
    "name": "University of Connecticut",
    "city": "Storrs",
    "state": "CT",
    "region": "Northeast",
    "usNewsRank": 69,
    "acceptanceRate": 0.544,
    "avgGpa": null,
    "satMid": 1340,
    "actMid": null,
    "tuitionUsd": null,
    "setting": "College town",
    "interests": "academics,research,campus life",
    "personalityFit": "balanced,ambitious",
    "extracurricularFit": "clubs,research,service,athletics",
    "vrTourUrl": "https://www.google.com/search?q=University%20of%20Connecticut%20virtual%20tour",
    "cdsUrl": "https://www.gradgpt.com/common-data-set",
    "websiteUrl": "https://uconn.edu/",
    "sizeBand": "Large"
  },
  {
    "id": "university-of-pittsburgh",
    "name": "University of Pittsburgh",
    "city": "Pittsburgh",
    "state": "PA",
    "region": "Northeast",
    "usNewsRank": 69,
    "acceptanceRate": 0.594,
    "avgGpa": null,
    "satMid": 1370,
    "actMid": 31,
    "tuitionUsd": null,
    "setting": "Urban",
    "interests": "academics,research,campus life",
    "personalityFit": "balanced,ambitious",
    "extracurricularFit": "clubs,research,service,athletics",
    "vrTourUrl": "https://www.google.com/search?q=University%20of%20Pittsburgh%20virtual%20tour",
    "cdsUrl": "https://www.gradgpt.com/common-data-set",
    "websiteUrl": "https://www.pitt.edu/",
    "sizeBand": "Large"
  },
  {
    "id": "binghamton-university",
    "name": "Binghamton University",
    "city": "Binghamton",
    "state": "NY",
    "region": "Northeast",
    "usNewsRank": 73,
    "acceptanceRate": null,
    "avgGpa": null,
    "satMid": null,
    "actMid": null,
    "tuitionUsd": null,
    "setting": "Suburban",
    "interests": "academics,research,campus life",
    "personalityFit": "balanced,ambitious",
    "extracurricularFit": "clubs,research,service,athletics",
    "vrTourUrl": "https://www.google.com/search?q=Binghamton%20University%20virtual%20tour",
    "cdsUrl": "https://www.collegedata.fyi/",
    "websiteUrl": "https://www.binghamton.edu/",
    "sizeBand": "Large"
  },
  {
    "id": "indiana-university-bloomington",
    "name": "Indiana University Bloomington",
    "city": "Bloomington",
    "state": "IN",
    "region": "Midwest",
    "usNewsRank": 73,
    "acceptanceRate": 0.759,
    "avgGpa": null,
    "satMid": 1305,
    "actMid": null,
    "tuitionUsd": null,
    "setting": "College town",
    "interests": "business,music,public affairs,informatics",
    "personalityFit": "outgoing,balanced",
    "extracurricularFit": "music,athletics,Greek life,clubs",
    "vrTourUrl": "https://admissions.indiana.edu/visit/virtual-visit.html",
    "cdsUrl": "https://www.gradgpt.com/common-data-set",
    "websiteUrl": "https://www.indiana.edu/",
    "sizeBand": "Large"
  },
  {
    "id": "clemson-university",
    "name": "Clemson University",
    "city": "Clemson",
    "state": "SC",
    "region": "South",
    "usNewsRank": 75,
    "acceptanceRate": 0.424,
    "avgGpa": null,
    "satMid": 1325,
    "actMid": null,
    "tuitionUsd": null,
    "setting": "College town",
    "interests": "academics,research,campus life",
    "personalityFit": "balanced,ambitious",
    "extracurricularFit": "clubs,research,service,athletics",
    "vrTourUrl": "https://www.google.com/search?q=Clemson%20University%20virtual%20tour",
    "cdsUrl": "https://www.gradgpt.com/common-data-set",
    "websiteUrl": "https://www.clemson.edu/",
    "sizeBand": "Large"
  },
  {
    "id": "rutgers-university-newark",
    "name": "Rutgers University-Newark",
    "city": "Newark",
    "state": "NJ",
    "region": "Northeast",
    "usNewsRank": 75,
    "acceptanceRate": null,
    "avgGpa": null,
    "satMid": null,
    "actMid": null,
    "tuitionUsd": null,
    "setting": "Urban",
    "interests": "academics,research,campus life",
    "personalityFit": "balanced,ambitious",
    "extracurricularFit": "clubs,research,service,athletics",
    "vrTourUrl": "https://www.google.com/search?q=Rutgers%20University-Newark%20virtual%20tour",
    "cdsUrl": "https://www.collegedata.fyi/",
    "websiteUrl": "https://www.newark.rutgers.edu/",
    "sizeBand": "Large"
  },
  {
    "id": "syracuse-university",
    "name": "Syracuse University",
    "city": "Syracuse",
    "state": "NY",
    "region": "Northeast",
    "usNewsRank": 75,
    "acceptanceRate": 0.43,
    "avgGpa": null,
    "satMid": 1345,
    "actMid": null,
    "tuitionUsd": null,
    "setting": "Urban",
    "interests": "academics,research,campus life",
    "personalityFit": "balanced,ambitious",
    "extracurricularFit": "clubs,research,service,athletics",
    "vrTourUrl": "https://www.google.com/search?q=Syracuse%20University%20virtual%20tour",
    "cdsUrl": "https://www.gradgpt.com/common-data-set",
    "websiteUrl": "https://www.syracuse.edu/",
    "sizeBand": "Large"
  },
  {
    "id": "university-at-buffalo",
    "name": "University at Buffalo",
    "city": "Buffalo",
    "state": "NY",
    "region": "Northeast",
    "usNewsRank": 75,
    "acceptanceRate": 0.806,
    "avgGpa": null,
    "satMid": 1295,
    "actMid": null,
    "tuitionUsd": null,
    "setting": "Suburban",
    "interests": "academics,research,campus life",
    "personalityFit": "balanced,ambitious",
    "extracurricularFit": "clubs,research,service,athletics",
    "vrTourUrl": "https://www.google.com/search?q=University%20at%20Buffalo%20virtual%20tour",
    "cdsUrl": "https://www.gradgpt.com/common-data-set",
    "websiteUrl": "https://www.buffalo.edu/",
    "sizeBand": "Large"
  },
  {
    "id": "university-of-california-riverside",
    "name": "University of California, Riverside",
    "city": "Riverside",
    "state": "CA",
    "region": "West",
    "usNewsRank": 75,
    "acceptanceRate": 0.769,
    "avgGpa": null,
    "satMid": null,
    "actMid": null,
    "tuitionUsd": null,
    "setting": "Suburban",
    "interests": "academics,research,campus life",
    "personalityFit": "balanced,ambitious",
    "extracurricularFit": "clubs,research,service,athletics",
    "vrTourUrl": "https://www.google.com/search?q=University%20of%20California%2C%20Riverside%20virtual%20tour",
    "cdsUrl": "https://www.gradgpt.com/common-data-set",
    "websiteUrl": "https://www.ucr.edu/",
    "sizeBand": "Large"
  },
  {
    "id": "colorado-school-of-mines",
    "name": "Colorado School of Mines",
    "city": "Golden",
    "state": "CO",
    "region": "West",
    "usNewsRank": 80,
    "acceptanceRate": 0.58,
    "avgGpa": null,
    "satMid": 1400,
    "actMid": null,
    "tuitionUsd": null,
    "setting": "Suburban",
    "interests": "academics,research,campus life",
    "personalityFit": "balanced,ambitious",
    "extracurricularFit": "clubs,research,service,athletics",
    "vrTourUrl": "https://www.google.com/search?q=Colorado%20School%20of%20Mines%20virtual%20tour",
    "cdsUrl": "https://www.gradgpt.com/common-data-set",
    "websiteUrl": "https://www.mines.edu/",
    "sizeBand": "Large"
  },
  {
    "id": "drexel-university",
    "name": "Drexel University",
    "city": "Philadelphia",
    "state": "PA",
    "region": "Northeast",
    "usNewsRank": 80,
    "acceptanceRate": null,
    "avgGpa": null,
    "satMid": null,
    "actMid": null,
    "tuitionUsd": null,
    "setting": "Urban",
    "interests": "academics,research,campus life",
    "personalityFit": "balanced,ambitious",
    "extracurricularFit": "clubs,research,service,athletics",
    "vrTourUrl": "https://www.google.com/search?q=Drexel%20University%20virtual%20tour",
    "cdsUrl": "https://www.collegedata.fyi/",
    "websiteUrl": "https://drexel.edu/",
    "sizeBand": "Large"
  },
  {
    "id": "new-jersey-institute-of-technology",
    "name": "New Jersey Institute of Technology",
    "city": "Newark",
    "state": "NJ",
    "region": "Northeast",
    "usNewsRank": 80,
    "acceptanceRate": null,
    "avgGpa": null,
    "satMid": null,
    "actMid": null,
    "tuitionUsd": null,
    "setting": "Urban",
    "interests": "academics,research,campus life",
    "personalityFit": "balanced,ambitious",
    "extracurricularFit": "clubs,research,service,athletics",
    "vrTourUrl": "https://www.google.com/search?q=New%20Jersey%20Institute%20of%20Technology%20virtual%20tour",
    "cdsUrl": "https://www.collegedata.fyi/",
    "websiteUrl": "https://www.njit.edu/",
    "sizeBand": "Large"
  },
  {
    "id": "stevens-institute-of-technology",
    "name": "Stevens Institute of Technology",
    "city": "Hoboken",
    "state": "NJ",
    "region": "Northeast",
    "usNewsRank": 80,
    "acceptanceRate": null,
    "avgGpa": null,
    "satMid": null,
    "actMid": null,
    "tuitionUsd": null,
    "setting": "Urban",
    "interests": "academics,research,campus life",
    "personalityFit": "balanced,ambitious",
    "extracurricularFit": "clubs,research,service,athletics",
    "vrTourUrl": "https://www.google.com/search?q=Stevens%20Institute%20of%20Technology%20virtual%20tour",
    "cdsUrl": "https://www.collegedata.fyi/",
    "websiteUrl": "https://www.stevens.edu/",
    "sizeBand": "Large"
  },
  {
    "id": "pepperdine-university",
    "name": "Pepperdine University",
    "city": "Malibu",
    "state": "CA",
    "region": "West",
    "usNewsRank": 84,
    "acceptanceRate": null,
    "avgGpa": null,
    "satMid": null,
    "actMid": null,
    "tuitionUsd": null,
    "setting": "Suburban",
    "interests": "academics,research,campus life",
    "personalityFit": "balanced,ambitious",
    "extracurricularFit": "clubs,research,service,athletics",
    "vrTourUrl": "https://www.google.com/search?q=Pepperdine%20University%20virtual%20tour",
    "cdsUrl": "https://www.collegedata.fyi/",
    "websiteUrl": "https://www.pepperdine.edu/",
    "sizeBand": "Large"
  },
  {
    "id": "university-of-illinois-chicago",
    "name": "University of Illinois Chicago",
    "city": "Chicago",
    "state": "IL",
    "region": "Midwest",
    "usNewsRank": 84,
    "acceptanceRate": 0.758,
    "avgGpa": 3.45,
    "satMid": 1170,
    "actMid": 27,
    "tuitionUsd": 28352,
    "setting": "Urban",
    "interests": "academics,research,campus life",
    "personalityFit": "balanced,ambitious",
    "extracurricularFit": "clubs,research,service,athletics",
    "vrTourUrl": "https://www.google.com/search?q=University%20of%20Illinois%20Chicago%20virtual%20tour",
    "cdsUrl": "https://www.collegedata.fyi/",
    "websiteUrl": "https://www.uic.edu/",
    "sizeBand": "Large"
  },
  {
    "id": "worcester-polytechnic-institute",
    "name": "Worcester Polytechnic Institute",
    "city": "Worcester",
    "state": "MA",
    "region": "Northeast",
    "usNewsRank": 84,
    "acceptanceRate": null,
    "avgGpa": null,
    "satMid": null,
    "actMid": null,
    "tuitionUsd": null,
    "setting": "Urban",
    "interests": "academics,research,campus life",
    "personalityFit": "balanced,ambitious",
    "extracurricularFit": "clubs,research,service,athletics",
    "vrTourUrl": "https://www.google.com/search?q=Worcester%20Polytechnic%20Institute%20virtual%20tour",
    "cdsUrl": "https://www.collegedata.fyi/",
    "websiteUrl": "https://www.wpi.edu/",
    "sizeBand": "Large"
  },
  {
    "id": "yeshiva-university",
    "name": "Yeshiva University",
    "city": "New York",
    "state": "NY",
    "region": "Northeast",
    "usNewsRank": 84,
    "acceptanceRate": null,
    "avgGpa": null,
    "satMid": null,
    "actMid": null,
    "tuitionUsd": null,
    "setting": "Urban",
    "interests": "academics,research,campus life",
    "personalityFit": "balanced,ambitious",
    "extracurricularFit": "clubs,research,service,athletics",
    "vrTourUrl": "https://www.google.com/search?q=Yeshiva%20University%20virtual%20tour",
    "cdsUrl": "https://www.collegedata.fyi/",
    "websiteUrl": "https://www.yu.edu/",
    "sizeBand": "Large"
  },
  {
    "id": "american-university",
    "name": "American University",
    "city": "Washington",
    "state": "DC",
    "region": "Northeast",
    "usNewsRank": 88,
    "acceptanceRate": null,
    "avgGpa": null,
    "satMid": null,
    "actMid": null,
    "tuitionUsd": null,
    "setting": "Urban",
    "interests": "academics,research,campus life",
    "personalityFit": "balanced,ambitious",
    "extracurricularFit": "clubs,research,service,athletics",
    "vrTourUrl": "https://www.google.com/search?q=American%20University%20virtual%20tour",
    "cdsUrl": "https://www.collegedata.fyi/",
    "websiteUrl": "https://www.american.edu/",
    "sizeBand": "Large"
  },
  {
    "id": "baylor-university",
    "name": "Baylor University",
    "city": "Waco",
    "state": "TX",
    "region": "South",
    "usNewsRank": 88,
    "acceptanceRate": 0.522,
    "avgGpa": null,
    "satMid": 1280,
    "actMid": null,
    "tuitionUsd": null,
    "setting": "Urban",
    "interests": "academics,research,campus life",
    "personalityFit": "balanced,ambitious",
    "extracurricularFit": "clubs,research,service,athletics",
    "vrTourUrl": "https://www.google.com/search?q=Baylor%20University%20virtual%20tour",
    "cdsUrl": "https://www.gradgpt.com/common-data-set",
    "websiteUrl": "https://www.baylor.edu/",
    "sizeBand": "Large"
  },
  {
    "id": "howard-university",
    "name": "Howard University",
    "city": "Washington",
    "state": "DC",
    "region": "Northeast",
    "usNewsRank": 88,
    "acceptanceRate": null,
    "avgGpa": 3.68,
    "satMid": null,
    "actMid": null,
    "tuitionUsd": 37996,
    "setting": "Urban",
    "interests": "academics,research,campus life",
    "personalityFit": "balanced,ambitious",
    "extracurricularFit": "clubs,research,service,athletics",
    "vrTourUrl": "https://www.google.com/search?q=Howard%20University%20virtual%20tour",
    "cdsUrl": "https://www.collegedata.fyi/",
    "websiteUrl": "https://www.howard.edu/",
    "sizeBand": "Large"
  },
  {
    "id": "marquette-university",
    "name": "Marquette University",
    "city": "Milwaukee",
    "state": "WI",
    "region": "Midwest",
    "usNewsRank": 88,
    "acceptanceRate": null,
    "avgGpa": null,
    "satMid": null,
    "actMid": null,
    "tuitionUsd": null,
    "setting": "Urban",
    "interests": "academics,research,campus life",
    "personalityFit": "balanced,ambitious",
    "extracurricularFit": "clubs,research,service,athletics",
    "vrTourUrl": "https://www.google.com/search?q=Marquette%20University%20virtual%20tour",
    "cdsUrl": "https://www.collegedata.fyi/",
    "websiteUrl": "https://www.marquette.edu/",
    "sizeBand": "Large"
  },
  {
    "id": "rochester-institute-of-technology",
    "name": "Rochester Institute of Technology",
    "city": "Rochester",
    "state": "NY",
    "region": "Northeast",
    "usNewsRank": 88,
    "acceptanceRate": null,
    "avgGpa": null,
    "satMid": null,
    "actMid": null,
    "tuitionUsd": null,
    "setting": "Suburban",
    "interests": "academics,research,campus life",
    "personalityFit": "balanced,ambitious",
    "extracurricularFit": "clubs,research,service,athletics",
    "vrTourUrl": "https://www.google.com/search?q=Rochester%20Institute%20of%20Technology%20virtual%20tour",
    "cdsUrl": "https://www.collegedata.fyi/",
    "websiteUrl": "https://www.rit.edu/",
    "sizeBand": "Large"
  },
  {
    "id": "southern-methodist-university",
    "name": "Southern Methodist University",
    "city": "Dallas",
    "state": "TX",
    "region": "South",
    "usNewsRank": 88,
    "acceptanceRate": null,
    "avgGpa": null,
    "satMid": null,
    "actMid": null,
    "tuitionUsd": null,
    "setting": "Urban",
    "interests": "academics,research,campus life",
    "personalityFit": "balanced,ambitious",
    "extracurricularFit": "clubs,research,service,athletics",
    "vrTourUrl": "https://www.google.com/search?q=Southern%20Methodist%20University%20virtual%20tour",
    "cdsUrl": "https://www.collegedata.fyi/",
    "websiteUrl": "https://www.smu.edu/",
    "sizeBand": "Large"
  },
  {
    "id": "university-of-california-santa-cruz",
    "name": "University of California, Santa Cruz",
    "city": "Santa Cruz",
    "state": "CA",
    "region": "West",
    "usNewsRank": 88,
    "acceptanceRate": null,
    "avgGpa": null,
    "satMid": null,
    "actMid": null,
    "tuitionUsd": null,
    "setting": "Suburban",
    "interests": "academics,research,campus life",
    "personalityFit": "balanced,ambitious",
    "extracurricularFit": "clubs,research,service,athletics",
    "vrTourUrl": "https://www.google.com/search?q=University%20of%20California%2C%20Santa%20Cruz%20virtual%20tour",
    "cdsUrl": "https://www.collegedata.fyi/",
    "websiteUrl": "https://www.ucsc.edu/",
    "sizeBand": "Large"
  },
  {
    "id": "university-of-delaware",
    "name": "University of Delaware",
    "city": "Newark",
    "state": "DE",
    "region": "Northeast",
    "usNewsRank": 88,
    "acceptanceRate": 0.692,
    "avgGpa": null,
    "satMid": 1295,
    "actMid": null,
    "tuitionUsd": null,
    "setting": "Suburban",
    "interests": "academics,research,campus life",
    "personalityFit": "balanced,ambitious",
    "extracurricularFit": "clubs,research,service,athletics",
    "vrTourUrl": "https://www.google.com/search?q=University%20of%20Delaware%20virtual%20tour",
    "cdsUrl": "https://www.gradgpt.com/common-data-set",
    "websiteUrl": "https://www.udel.edu/",
    "sizeBand": "Large"
  },
  {
    "id": "university-of-south-florida",
    "name": "University of South Florida",
    "city": "Tampa",
    "state": "FL",
    "region": "South",
    "usNewsRank": 88,
    "acceptanceRate": 0.407,
    "avgGpa": null,
    "satMid": 1250,
    "actMid": null,
    "tuitionUsd": null,
    "setting": "Urban",
    "interests": "pre-med,business,engineering,sciences",
    "personalityFit": "ambitious,outgoing",
    "extracurricularFit": "athletics,research,Greek life,service",
    "vrTourUrl": "https://admissions.ufl.edu/visit/virtual-tour/",
    "cdsUrl": "https://www.gradgpt.com/common-data-set",
    "websiteUrl": "https://www.usf.edu/",
    "sizeBand": "Large"
  },
  {
    "id": "florida-international-university",
    "name": "Florida International University",
    "city": "Miami",
    "state": "FL",
    "region": "South",
    "usNewsRank": 97,
    "acceptanceRate": null,
    "avgGpa": null,
    "satMid": null,
    "actMid": null,
    "tuitionUsd": null,
    "setting": "Urban",
    "interests": "pre-med,business,engineering,sciences",
    "personalityFit": "ambitious,outgoing",
    "extracurricularFit": "athletics,research,Greek life,service",
    "vrTourUrl": "https://admissions.ufl.edu/visit/virtual-tour/",
    "cdsUrl": "https://www.collegedata.fyi/",
    "websiteUrl": "https://www.fiu.edu/",
    "sizeBand": "Large"
  },
  {
    "id": "fordham-university",
    "name": "Fordham University",
    "city": "New York",
    "state": "NY",
    "region": "Northeast",
    "usNewsRank": 97,
    "acceptanceRate": null,
    "avgGpa": null,
    "satMid": null,
    "actMid": null,
    "tuitionUsd": null,
    "setting": "Urban",
    "interests": "academics,research,campus life",
    "personalityFit": "balanced,ambitious",
    "extracurricularFit": "clubs,research,service,athletics",
    "vrTourUrl": "https://www.google.com/search?q=Fordham%20University%20virtual%20tour",
    "cdsUrl": "https://www.collegedata.fyi/",
    "websiteUrl": "https://www.fordham.edu/",
    "sizeBand": "Large"
  },
  {
    "id": "rutgers-university-camden",
    "name": "Rutgers University-Camden",
    "city": "Camden",
    "state": "NJ",
    "region": "Northeast",
    "usNewsRank": 97,
    "acceptanceRate": null,
    "avgGpa": null,
    "satMid": null,
    "actMid": null,
    "tuitionUsd": null,
    "setting": "Urban",
    "interests": "academics,research,campus life",
    "personalityFit": "balanced,ambitious",
    "extracurricularFit": "clubs,research,service,athletics",
    "vrTourUrl": "https://www.google.com/search?q=Rutgers%20University-Camden%20virtual%20tour",
    "cdsUrl": "https://www.collegedata.fyi/",
    "websiteUrl": "https://www.camden.rutgers.edu/",
    "sizeBand": "Large"
  },
  {
    "id": "texas-christian-university",
    "name": "Texas Christian University",
    "city": "Fort Worth",
    "state": "TX",
    "region": "South",
    "usNewsRank": 97,
    "acceptanceRate": null,
    "avgGpa": null,
    "satMid": null,
    "actMid": null,
    "tuitionUsd": null,
    "setting": "Suburban",
    "interests": "academics,research,campus life",
    "personalityFit": "balanced,ambitious",
    "extracurricularFit": "clubs,research,service,athletics",
    "vrTourUrl": "https://www.google.com/search?q=Texas%20Christian%20University%20virtual%20tour",
    "cdsUrl": "https://www.collegedata.fyi/",
    "websiteUrl": "https://www.tcu.edu/",
    "sizeBand": "Large"
  },
  {
    "id": "university-of-colorado-boulder",
    "name": "University of Colorado Boulder",
    "city": "Boulder",
    "state": "CO",
    "region": "West",
    "usNewsRank": 97,
    "acceptanceRate": 0.76,
    "avgGpa": null,
    "satMid": 1285,
    "actMid": null,
    "tuitionUsd": null,
    "setting": "College town",
    "interests": "environmental science,engineering,business,outdoors",
    "personalityFit": "adventurous,balanced",
    "extracurricularFit": "outdoors,athletics,sustainability,clubs",
    "vrTourUrl": "https://www.colorado.edu/admissions/visit/virtual-tour",
    "cdsUrl": "https://www.gradgpt.com/common-data-set",
    "websiteUrl": "https://www.colorado.edu/",
    "sizeBand": "Large"
  },
  {
    "id": "auburn-university",
    "name": "Auburn University",
    "city": "Auburn",
    "state": "AL",
    "region": "South",
    "usNewsRank": 102,
    "acceptanceRate": 0.46,
    "avgGpa": 4.09,
    "satMid": 1290,
    "actMid": 28,
    "tuitionUsd": 33048,
    "setting": "College town",
    "interests": "academics,research,campus life",
    "personalityFit": "balanced,ambitious",
    "extracurricularFit": "clubs,research,service,athletics",
    "vrTourUrl": "https://www.google.com/search?q=Auburn%20University%20virtual%20tour",
    "cdsUrl": "https://www.gradgpt.com/common-data-set",
    "websiteUrl": "https://www.auburn.edu/",
    "sizeBand": "Large"
  },
  {
    "id": "gonzaga-university",
    "name": "Gonzaga University",
    "city": "Spokane",
    "state": "WA",
    "region": "West",
    "usNewsRank": 102,
    "acceptanceRate": null,
    "avgGpa": null,
    "satMid": null,
    "actMid": null,
    "tuitionUsd": null,
    "setting": "Urban",
    "interests": "academics,research,campus life",
    "personalityFit": "balanced,ambitious",
    "extracurricularFit": "clubs,research,service,athletics",
    "vrTourUrl": "https://www.google.com/search?q=Gonzaga%20University%20virtual%20tour",
    "cdsUrl": "https://www.collegedata.fyi/",
    "websiteUrl": "https://www.gonzaga.edu/",
    "sizeBand": "Large"
  },
  {
    "id": "loyola-marymount-university",
    "name": "Loyola Marymount University",
    "city": "Los Angeles",
    "state": "CA",
    "region": "West",
    "usNewsRank": 102,
    "acceptanceRate": null,
    "avgGpa": null,
    "satMid": null,
    "actMid": null,
    "tuitionUsd": null,
    "setting": "Suburban",
    "interests": "academics,research,campus life",
    "personalityFit": "balanced,ambitious",
    "extracurricularFit": "clubs,research,service,athletics",
    "vrTourUrl": "https://www.google.com/search?q=Loyola%20Marymount%20University%20virtual%20tour",
    "cdsUrl": "https://www.collegedata.fyi/",
    "websiteUrl": "https://www.lmu.edu/",
    "sizeBand": "Large"
  },
  {
    "id": "saint-louis-university",
    "name": "Saint Louis University",
    "city": "St. Louis",
    "state": "MO",
    "region": "Midwest",
    "usNewsRank": 102,
    "acceptanceRate": null,
    "avgGpa": null,
    "satMid": null,
    "actMid": null,
    "tuitionUsd": null,
    "setting": "Urban",
    "interests": "academics,research,campus life",
    "personalityFit": "balanced,ambitious",
    "extracurricularFit": "clubs,research,service,athletics",
    "vrTourUrl": "https://www.google.com/search?q=Saint%20Louis%20University%20virtual%20tour",
    "cdsUrl": "https://www.collegedata.fyi/",
    "websiteUrl": "https://www.slu.edu/",
    "sizeBand": "Large"
  },
  {
    "id": "temple-university",
    "name": "Temple University",
    "city": "Philadelphia",
    "state": "PA",
    "region": "Northeast",
    "usNewsRank": 102,
    "acceptanceRate": null,
    "avgGpa": null,
    "satMid": null,
    "actMid": null,
    "tuitionUsd": null,
    "setting": "Urban",
    "interests": "academics,research,campus life",
    "personalityFit": "balanced,ambitious",
    "extracurricularFit": "clubs,research,service,athletics",
    "vrTourUrl": "https://www.google.com/search?q=Temple%20University%20virtual%20tour",
    "cdsUrl": "https://www.collegedata.fyi/",
    "websiteUrl": "https://www.temple.edu/",
    "sizeBand": "Large"
  },
  {
    "id": "university-of-iowa",
    "name": "University of Iowa",
    "city": "Iowa City",
    "state": "IA",
    "region": "Midwest",
    "usNewsRank": 102,
    "acceptanceRate": 0.799,
    "avgGpa": null,
    "satMid": 1225,
    "actMid": null,
    "tuitionUsd": null,
    "setting": "College town",
    "interests": "academics,research,campus life",
    "personalityFit": "balanced,ambitious",
    "extracurricularFit": "clubs,research,service,athletics",
    "vrTourUrl": "https://www.google.com/search?q=University%20of%20Iowa%20virtual%20tour",
    "cdsUrl": "https://www.gradgpt.com/common-data-set",
    "websiteUrl": "https://uiowa.edu/",
    "sizeBand": "Large"
  },
  {
    "id": "university-of-missouri",
    "name": "University of Missouri",
    "city": "Columbia",
    "state": "MO",
    "region": "Midwest",
    "usNewsRank": 102,
    "acceptanceRate": 0.785,
    "avgGpa": null,
    "satMid": 1240,
    "actMid": null,
    "tuitionUsd": null,
    "setting": "College town",
    "interests": "academics,research,campus life",
    "personalityFit": "balanced,ambitious",
    "extracurricularFit": "clubs,research,service,athletics",
    "vrTourUrl": "https://www.google.com/search?q=University%20of%20Missouri%20virtual%20tour",
    "cdsUrl": "https://www.gradgpt.com/common-data-set",
    "websiteUrl": "https://missouri.edu/",
    "sizeBand": "Large"
  },
  {
    "id": "university-of-tennessee-knoxville",
    "name": "University of Tennessee, Knoxville",
    "city": "Knoxville",
    "state": "TN",
    "region": "South",
    "usNewsRank": 102,
    "acceptanceRate": 0.436,
    "avgGpa": null,
    "satMid": 1330,
    "actMid": null,
    "tuitionUsd": null,
    "setting": "Urban",
    "interests": "academics,research,campus life",
    "personalityFit": "balanced,ambitious",
    "extracurricularFit": "clubs,research,service,athletics",
    "vrTourUrl": "https://www.google.com/search?q=University%20of%20Tennessee%2C%20Knoxville%20virtual%20tour",
    "cdsUrl": "https://www.gradgpt.com/common-data-set",
    "websiteUrl": "https://www.utk.edu/",
    "sizeBand": "Large"
  }
];

export function searchUniversities(q: string) {
  const query = q.trim().toLowerCase();
  if (!query) return UNIVERSITIES;
  return UNIVERSITIES.filter(
    (u) =>
      u.name.toLowerCase().includes(query) ||
      u.city.toLowerCase().includes(query) ||
      u.state.toLowerCase().includes(query) ||
      u.region.toLowerCase().includes(query)
  );
}

export function formatAcceptance(rate: number | null) {
  if (rate == null) return "—";
  return `${(rate * 100).toFixed(1)}%`;
}
