export type University = {
  id: string;
  name: string;
  city: string;
  state: string;
  region: string;
  acceptanceRate: number;
  avgGpa: number;
  satMid: number;
  actMid: number;
  setting: string;
  interests: string;
  personalityFit: string;
  extracurricularFit: string;
  vrTourUrl: string;
  cdsUrl: string;
  websiteUrl: string;
  sizeBand: string;
};

export const UNIVERSITIES: University[] = [
  {
    id: "stanford",
    name: "Stanford University",
    city: "Stanford",
    state: "CA",
    region: "West",
    acceptanceRate: 0.04,
    avgGpa: 3.96,
    satMid: 1545,
    actMid: 35,
    setting: "Suburban",
    interests: "CS,engineering,entrepreneurship,research",
    personalityFit: "ambitious,innovator",
    extracurricularFit: "research,robotics,startups,debate",
    vrTourUrl: "https://tour.stanford.edu/",
    cdsUrl: "https://irds.stanford.edu/data-findings/cds",
    websiteUrl: "https://www.stanford.edu/",
    sizeBand: "Large",
  },
  {
    id: "mit",
    name: "Massachusetts Institute of Technology",
    city: "Cambridge",
    state: "MA",
    region: "Northeast",
    acceptanceRate: 0.04,
    avgGpa: 3.95,
    satMid: 1550,
    actMid: 35,
    setting: "Urban",
    interests: "engineering,CS,physics,innovation",
    personalityFit: "analytical,innovator",
    extracurricularFit: "research,hackathons,robotics,maker",
    vrTourUrl: "https://mitadmissions.org/visit/virtual-programs/",
    cdsUrl: "https://ir.mit.edu/common-data-set",
    websiteUrl: "https://www.mit.edu/",
    sizeBand: "Medium",
  },
  {
    id: "harvard",
    name: "Harvard University",
    city: "Cambridge",
    state: "MA",
    region: "Northeast",
    acceptanceRate: 0.03,
    avgGpa: 4.0,
    satMid: 1540,
    actMid: 35,
    setting: "Urban",
    interests: "government,law,medicine,research",
    personalityFit: "ambitious,leader",
    extracurricularFit: "debate,research,community service,politics",
    vrTourUrl: "https://college.harvard.edu/admissions/visit/virtual-tour",
    cdsUrl: "https://oir.harvard.edu/common-data-set",
    websiteUrl: "https://www.harvard.edu/",
    sizeBand: "Large",
  },
  {
    id: "yale",
    name: "Yale University",
    city: "New Haven",
    state: "CT",
    region: "Northeast",
    acceptanceRate: 0.05,
    avgGpa: 3.95,
    satMid: 1530,
    actMid: 34,
    setting: "Urban",
    interests: "arts,humanities,law,science",
    personalityFit: "creative,intellectual",
    extracurricularFit: "theater,writing,research,activism",
    vrTourUrl: "https://admissions.yale.edu/virtual-events",
    cdsUrl: "https://oir.yale.edu/common-data-set",
    websiteUrl: "https://www.yale.edu/",
    sizeBand: "Medium",
  },
  {
    id: "princeton",
    name: "Princeton University",
    city: "Princeton",
    state: "NJ",
    region: "Northeast",
    acceptanceRate: 0.06,
    avgGpa: 3.94,
    satMid: 1535,
    actMid: 34,
    setting: "Suburban",
    interests: "engineering,public policy,research",
    personalityFit: "intellectual,ambitious",
    extracurricularFit: "research,debate,service,athletics",
    vrTourUrl: "https://admission.princeton.edu/visit-princeton/virtual-visit",
    cdsUrl: "https://registrar.princeton.edu/university-common-data-set",
    websiteUrl: "https://www.princeton.edu/",
    sizeBand: "Medium",
  },
  {
    id: "berkeley",
    name: "University of California, Berkeley",
    city: "Berkeley",
    state: "CA",
    region: "West",
    acceptanceRate: 0.11,
    avgGpa: 3.9,
    satMid: 1455,
    actMid: 33,
    setting: "Urban",
    interests: "CS,engineering,social impact,research",
    personalityFit: "activist,analytical",
    extracurricularFit: "research,activism,entrepreneurship,clubs",
    vrTourUrl: "https://visit.berkeley.edu/virtual-tour/",
    cdsUrl: "https://opa.berkeley.edu/campus-data/common-data-set",
    websiteUrl: "https://www.berkeley.edu/",
    sizeBand: "Large",
  },
  {
    id: "ucla",
    name: "University of California, Los Angeles",
    city: "Los Angeles",
    state: "CA",
    region: "West",
    acceptanceRate: 0.09,
    avgGpa: 3.92,
    satMid: 1440,
    actMid: 32,
    setting: "Urban",
    interests: "film,medicine,business,arts",
    personalityFit: "creative,outgoing",
    extracurricularFit: "film,athletics,performing arts,service",
    vrTourUrl: "https://tour.ucla.edu/",
    cdsUrl: "https://apb.ucla.edu/campus-statistics/common-data-set",
    websiteUrl: "https://www.ucla.edu/",
    sizeBand: "Large",
  },
  {
    id: "umich",
    name: "University of Michigan",
    city: "Ann Arbor",
    state: "MI",
    region: "Midwest",
    acceptanceRate: 0.18,
    avgGpa: 3.88,
    satMid: 1440,
    actMid: 33,
    setting: "College town",
    interests: "business,engineering,public policy",
    personalityFit: "balanced,leader",
    extracurricularFit: "athletics,research,Greek life,clubs",
    vrTourUrl: "https://campusinfo.umich.edu/tour",
    cdsUrl: "https://obp.umich.edu/root/common-data-set/",
    websiteUrl: "https://umich.edu/",
    sizeBand: "Large",
  },
  {
    id: "uva",
    name: "University of Virginia",
    city: "Charlottesville",
    state: "VA",
    region: "South",
    acceptanceRate: 0.19,
    avgGpa: 3.9,
    satMid: 1450,
    actMid: 33,
    setting: "College town",
    interests: "liberal arts,business,law,public service",
    personalityFit: "traditional,leader",
    extracurricularFit: "honor societies,service,athletics,debate",
    vrTourUrl: "https://admission.virginia.edu/visit/virtual-events",
    cdsUrl: "https://ira.virginia.edu/university-data/common-data-set",
    websiteUrl: "https://www.virginia.edu/",
    sizeBand: "Large",
  },
  {
    id: "unc",
    name: "University of North Carolina at Chapel Hill",
    city: "Chapel Hill",
    state: "NC",
    region: "South",
    acceptanceRate: 0.17,
    avgGpa: 3.85,
    satMid: 1420,
    actMid: 31,
    setting: "College town",
    interests: "public health,journalism,business,research",
    personalityFit: "balanced,outgoing",
    extracurricularFit: "athletics,service,research,media",
    vrTourUrl: "https://admissions.unc.edu/visit/virtual-visit/",
    cdsUrl: "https://oira.unc.edu/reports/common-data-set/",
    websiteUrl: "https://www.unc.edu/",
    sizeBand: "Large",
  },
  {
    id: "gatech",
    name: "Georgia Institute of Technology",
    city: "Atlanta",
    state: "GA",
    region: "South",
    acceptanceRate: 0.16,
    avgGpa: 3.9,
    satMid: 1465,
    actMid: 33,
    setting: "Urban",
    interests: "engineering,CS,computing,innovation",
    personalityFit: "analytical,innovator",
    extracurricularFit: "hackathons,research,robotics,STEM clubs",
    vrTourUrl: "https://admission.gatech.edu/visit/virtual-visit",
    cdsUrl: "https://irp.gatech.edu/common-data-set",
    websiteUrl: "https://www.gatech.edu/",
    sizeBand: "Large",
  },
  {
    id: "utexas",
    name: "University of Texas at Austin",
    city: "Austin",
    state: "TX",
    region: "South",
    acceptanceRate: 0.29,
    avgGpa: 3.84,
    satMid: 1370,
    actMid: 30,
    setting: "Urban",
    interests: "business,engineering,CS,communications",
    personalityFit: "entrepreneurial,outgoing",
    extracurricularFit: "startups,athletics,music,clubs",
    vrTourUrl: "https://visit.utexas.edu/virtual-tour/",
    cdsUrl: "https://reports.utexas.edu/common-data-set",
    websiteUrl: "https://www.utexas.edu/",
    sizeBand: "Large",
  },
  {
    id: "uw",
    name: "University of Washington",
    city: "Seattle",
    state: "WA",
    region: "West",
    acceptanceRate: 0.48,
    avgGpa: 3.8,
    satMid: 1340,
    actMid: 30,
    setting: "Urban",
    interests: "CS,engineering,environmental science,medicine",
    personalityFit: "analytical,collaborative",
    extracurricularFit: "research,outdoors,tech clubs,service",
    vrTourUrl: "https://www.washington.edu/visit/virtual-tour/",
    cdsUrl: "https://studentdata.washington.edu/cds/",
    websiteUrl: "https://www.washington.edu/",
    sizeBand: "Large",
  },
  {
    id: "wisc",
    name: "University of WisconsinÔÇôMadison",
    city: "Madison",
    state: "WI",
    region: "Midwest",
    acceptanceRate: 0.49,
    avgGpa: 3.85,
    satMid: 1390,
    actMid: 30,
    setting: "College town",
    interests: "research,business,agriculture,engineering",
    personalityFit: "balanced,outgoing",
    extracurricularFit: "athletics,research,outdoors,clubs",
    vrTourUrl: "https://www.visit.wisc.edu/virtual-tour/",
    cdsUrl: "https://apir.wisc.edu/data-digest/common-data-set/",
    websiteUrl: "https://www.wisc.edu/",
    sizeBand: "Large",
  },
  {
    id: "osu",
    name: "Ohio State University",
    city: "Columbus",
    state: "OH",
    region: "Midwest",
    acceptanceRate: 0.53,
    avgGpa: 3.76,
    satMid: 1340,
    actMid: 29,
    setting: "Urban",
    interests: "business,engineering,health,agriculture",
    personalityFit: "outgoing,leader",
    extracurricularFit: "athletics,Greek life,research,clubs",
    vrTourUrl: "https://visit.osu.edu/virtual-tour",
    cdsUrl: "https://oaa.osu.edu/institutional-data/common-data-set",
    websiteUrl: "https://www.osu.edu/",
    sizeBand: "Large",
  },
  {
    id: "psu",
    name: "Pennsylvania State University",
    city: "University Park",
    state: "PA",
    region: "Northeast",
    acceptanceRate: 0.55,
    avgGpa: 3.7,
    satMid: 1290,
    actMid: 29,
    setting: "College town",
    interests: "engineering,business,communications,science",
    personalityFit: "balanced,outgoing",
    extracurricularFit: "athletics,clubs,research,Greek life",
    vrTourUrl: "https://admissions.psu.edu/visit/virtual/",
    cdsUrl: "https://datadigest.psu.edu/common-data-set/",
    websiteUrl: "https://www.psu.edu/",
    sizeBand: "Large",
  },
  {
    id: "purdue",
    name: "Purdue University",
    city: "West Lafayette",
    state: "IN",
    region: "Midwest",
    acceptanceRate: 0.53,
    avgGpa: 3.74,
    satMid: 1330,
    actMid: 30,
    setting: "College town",
    interests: "engineering,aviation,agriculture,CS",
    personalityFit: "analytical,practical",
    extracurricularFit: "STEM clubs,research,athletics,maker",
    vrTourUrl: "https://www.purdue.edu/visit/virtual-tour/",
    cdsUrl: "https://www.purdue.edu/datadigest/CDS/",
    websiteUrl: "https://www.purdue.edu/",
    sizeBand: "Large",
  },
  {
    id: "ufl",
    name: "University of Florida",
    city: "Gainesville",
    state: "FL",
    region: "South",
    acceptanceRate: 0.23,
    avgGpa: 3.9,
    satMid: 1390,
    actMid: 31,
    setting: "College town",
    interests: "pre-med,business,engineering,sciences",
    personalityFit: "ambitious,outgoing",
    extracurricularFit: "athletics,research,Greek life,service",
    vrTourUrl: "https://admissions.ufl.edu/visit/virtual-tour/",
    cdsUrl: "https://ir.aa.ufl.edu/reports/common-data-set/",
    websiteUrl: "https://www.ufl.edu/",
    sizeBand: "Large",
  },
  {
    id: "uiuc",
    name: "University of Illinois Urbana-Champaign",
    city: "Champaign",
    state: "IL",
    region: "Midwest",
    acceptanceRate: 0.44,
    avgGpa: 3.8,
    satMid: 1410,
    actMid: 31,
    setting: "College town",
    interests: "CS,engineering,business,research",
    personalityFit: "analytical,collaborative",
    extracurricularFit: "hackathons,research,clubs,athletics",
    vrTourUrl: "https://admissions.illinois.edu/visit/virtual-tour",
    cdsUrl: "https://dmi.illinois.edu/stuenr/cds.htm",
    websiteUrl: "https://illinois.edu/",
    sizeBand: "Large",
  },
  {
    id: "nyu",
    name: "New York University",
    city: "New York",
    state: "NY",
    region: "Northeast",
    acceptanceRate: 0.13,
    avgGpa: 3.8,
    satMid: 1480,
    actMid: 33,
    setting: "Urban",
    interests: "arts,business,film,international studies",
    personalityFit: "creative,cosmopolitan",
    extracurricularFit: "arts,internships,media,entrepreneurship",
    vrTourUrl:
      "https://www.nyu.edu/admissions/undergraduate-admissions/visit/virtual-tour.html",
    cdsUrl:
      "https://www.nyu.edu/employees/resources-and-services/administrative-services/institutional-research/common-data-set.html",
    websiteUrl: "https://www.nyu.edu/",
    sizeBand: "Large",
  },
  {
    id: "usc",
    name: "University of Southern California",
    city: "Los Angeles",
    state: "CA",
    region: "West",
    acceptanceRate: 0.1,
    avgGpa: 3.88,
    satMid: 1470,
    actMid: 33,
    setting: "Urban",
    interests: "film,business,engineering,communications",
    personalityFit: "creative,outgoing",
    extracurricularFit: "film,athletics,entrepreneurship,arts",
    vrTourUrl: "https://admission.usc.edu/learn/visit-usc/virtual-tour/",
    cdsUrl: "https://oir.usc.edu/common-data-set/",
    websiteUrl: "https://www.usc.edu/",
    sizeBand: "Large",
  },
  {
    id: "cmu",
    name: "Carnegie Mellon University",
    city: "Pittsburgh",
    state: "PA",
    region: "Northeast",
    acceptanceRate: 0.11,
    avgGpa: 3.9,
    satMid: 1520,
    actMid: 34,
    setting: "Urban",
    interests: "CS,engineering,drama,design",
    personalityFit: "analytical,creative",
    extracurricularFit: "hackathons,theater,research,design",
    vrTourUrl: "https://www.cmu.edu/admission/visit/virtual",
    cdsUrl: "https://www.cmu.edu/ira/cds/",
    websiteUrl: "https://www.cmu.edu/",
    sizeBand: "Medium",
  },
  {
    id: "duke",
    name: "Duke University",
    city: "Durham",
    state: "NC",
    region: "South",
    acceptanceRate: 0.06,
    avgGpa: 3.94,
    satMid: 1525,
    actMid: 34,
    setting: "Suburban",
    interests: "medicine,public policy,engineering,research",
    personalityFit: "ambitious,leader",
    extracurricularFit: "athletics,research,service,debate",
    vrTourUrl: "https://admissions.duke.edu/visit/virtual-experiences/",
    cdsUrl: "https://registrar.duke.edu/common-data-set",
    websiteUrl: "https://www.duke.edu/",
    sizeBand: "Medium",
  },
  {
    id: "northwestern",
    name: "Northwestern University",
    city: "Evanston",
    state: "IL",
    region: "Midwest",
    acceptanceRate: 0.07,
    avgGpa: 3.92,
    satMid: 1510,
    actMid: 34,
    setting: "Suburban",
    interests: "journalism,engineering,business,arts",
    personalityFit: "creative,ambitious",
    extracurricularFit: "media,research,performance,debate",
    vrTourUrl:
      "https://admissions.northwestern.edu/visit/virtual-opportunities.html",
    cdsUrl:
      "https://www.northwestern.edu/provost/planning-analytics/institutional-research/common-data-set.html",
    websiteUrl: "https://www.northwestern.edu/",
    sizeBand: "Medium",
  },
  {
    id: "colorado",
    name: "University of Colorado Boulder",
    city: "Boulder",
    state: "CO",
    region: "West",
    acceptanceRate: 0.81,
    avgGpa: 3.7,
    satMid: 1270,
    actMid: 28,
    setting: "College town",
    interests: "environmental science,engineering,business,outdoors",
    personalityFit: "adventurous,balanced",
    extracurricularFit: "outdoors,athletics,sustainability,clubs",
    vrTourUrl: "https://www.colorado.edu/admissions/visit/virtual-tour",
    cdsUrl: "https://www.colorado.edu/oda/institutional-research/common-data-set",
    websiteUrl: "https://www.colorado.edu/",
    sizeBand: "Large",
  },
  {
    id: "asu",
    name: "Arizona State University",
    city: "Tempe",
    state: "AZ",
    region: "West",
    acceptanceRate: 0.9,
    avgGpa: 3.54,
    satMid: 1240,
    actMid: 25,
    setting: "Urban",
    interests: "business,innovation,engineering,online learning",
    personalityFit: "entrepreneurial,practical",
    extracurricularFit: "entrepreneurship,athletics,clubs,service",
    vrTourUrl: "https://visit.asu.edu/virtual-tour",
    cdsUrl: "https://uoia.asu.edu/content/common-data-set",
    websiteUrl: "https://www.asu.edu/",
    sizeBand: "Large",
  },
  {
    id: "oregon",
    name: "University of Oregon",
    city: "Eugene",
    state: "OR",
    region: "West",
    acceptanceRate: 0.86,
    avgGpa: 3.65,
    satMid: 1230,
    actMid: 26,
    setting: "College town",
    interests: "journalism,business,environmental studies,arts",
    personalityFit: "creative,adventurous",
    extracurricularFit: "outdoors,athletics,media,arts",
    vrTourUrl: "https://www.uoregon.edu/admissions/visit/virtual-tour",
    cdsUrl: "https://ir.uoregon.edu/common-data-set",
    websiteUrl: "https://www.uoregon.edu/",
    sizeBand: "Large",
  },
  {
    id: "indiana",
    name: "Indiana University Bloomington",
    city: "Bloomington",
    state: "IN",
    region: "Midwest",
    acceptanceRate: 0.8,
    avgGpa: 3.75,
    satMid: 1280,
    actMid: 28,
    setting: "College town",
    interests: "business,music,public affairs,informatics",
    personalityFit: "outgoing,balanced",
    extracurricularFit: "music,athletics,Greek life,clubs",
    vrTourUrl: "https://admissions.indiana.edu/visit/virtual-visit.html",
    cdsUrl: "https://uirr.iu.edu/facts-figures/common-data-set/index.html",
    websiteUrl: "https://www.indiana.edu/",
    sizeBand: "Large",
  },
  {
    id: "bu",
    name: "Boston University",
    city: "Boston",
    state: "MA",
    region: "Northeast",
    acceptanceRate: 0.14,
    avgGpa: 3.8,
    satMid: 1430,
    actMid: 32,
    setting: "Urban",
    interests: "communications,business,international relations,pre-med",
    personalityFit: "ambitious,cosmopolitan",
    extracurricularFit: "internships,research,media,service",
    vrTourUrl: "https://www.bu.edu/admissions/visit-bu/virtual-tour/",
    cdsUrl:
      "https://www.bu.edu/provost/planning-resources/institutional-research/common-data-set/",
    websiteUrl: "https://www.bu.edu/",
    sizeBand: "Large",
  },
  {
    id: "miami",
    name: "University of Miami",
    city: "Coral Gables",
    state: "FL",
    region: "South",
    acceptanceRate: 0.19,
    avgGpa: 3.75,
    satMid: 1380,
    actMid: 31,
    setting: "Suburban",
    interests: "marine science,business,communications,music",
    personalityFit: "outgoing,creative",
    extracurricularFit: "athletics,music,research,service",
    vrTourUrl:
      "https://admissions.miami.edu/undergraduate/visit/virtual-tour/index.html",
    cdsUrl: "https://oire.miami.edu/facts-and-stats/common-data-set/index.html",
    websiteUrl: "https://www.miami.edu/",
    sizeBand: "Medium",
  },
];

export function searchUniversities(q: string) {
  const query = q.trim().toLowerCase();
  if (!query) return UNIVERSITIES;
  return UNIVERSITIES.filter(
    (u) =>
      u.name.toLowerCase().includes(query) ||
      u.city.toLowerCase().includes(query) ||
      u.state.toLowerCase().includes(query) ||
      u.region.toLowerCase().includes(query)
  );
}
